from pathlib import Path
import json, re, hashlib, datetime
W=Path.cwd(); E=W/'docs/reviews/framework-platforms-20260909'; D=E/'official-hono-supabase'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
cat={}
for p in D.glob('*manifest*.json'):
 for o in json.loads(p.read_text()):
  if o.get('file') and (D/o['file']).exists():cat[o['id']]=o
for k,u in {'cf-compat-flags':'https://raw.githubusercontent.com/cloudflare/cloudflare-docs/production/src/content/docs/workers/configuration/compatibility-flags.mdx','workerd-compat':'https://raw.githubusercontent.com/cloudflare/workerd/main/src/workerd/io/compatibility-date.capnp','sdk-retry':'https://raw.githubusercontent.com/supabase/supabase-js/v2.116.0/packages/core/postgrest-js/src/fetchWithRetry.ts','sdk-retry-common':'https://raw.githubusercontent.com/supabase/supabase-js/v2.116.0/packages/core/postgrest-js/src/types/common/common.ts'}.items():
 p=D/(k+'.txt');cat[k]={'id':k,'url':u,'file':p.name,'retrievedAt':datetime.datetime.fromtimestamp(p.stat().st_mtime,datetime.timezone.utc).isoformat(),'retrievedAtBasis':'file mtime from recorded official fetch','sha256':sha(p)}
for o in cat.values():
 o['snapshot']='official-hono-supabase/'+o['file'];o['sha256Readback']=sha(D/o['file']);o['readbackMatches']=o.get('sha256')==o['sha256Readback'];o['channel']='pinned stable release source' if re.search(r'/v[0-9]',o['url']) else 'official rolling documentation/source, or stable release metadata; captured 2026-09-09'
(E/'official-hono-supabase-sources.json').write_text(json.dumps(list(cat.values()),ensure_ascii=False,indent=2)+'\n')
# Every active reference is assigned sources, scoped conclusion, delta and a falsifier. Fine-grained section/paragraph/code locations are emitted below.
H={
'architecture':(['hono-api-routing','hono-helpers-factory','hono-guides-rpc'],'app.route, chained schema inference and factory helpers are supported. Layering and topology stay project-owned.','none','A chained route/client fixture loses a declared route or the agent invents a layer.'),
'auth':(['hono-bearer-source','hono-middleware-builtin-jwt','hono-middleware-builtin-jwk','hono-middleware-builtin-csrf','hono-middleware-builtin-combine','hono-helpers-streaming'],'JWT explicit alg, JWK kid/asymmetric selection, csrf OR semantics, some/every/except and abort cleanup agree with current sources. Bearer configuration claim is incorrect.','H01','Exercise malformed Authorization, missing header, valid mismatch and middleware construction separately.'),
'caching':(['hono-middleware-builtin-etag','hono-middleware-builtin-cache','cf-runtime-apis-cache'],'ETag/cache APIs supported; CF Cache API skips Set-Cookie unless removed or private=Set-Cookie; locality is not global consistency. Privacy/freshness remain accepted policy.','none','A private response crosses identities or a Set-Cookie response is claimed cached without platform observation.'),
'contracts-types':(['hono-guides-rpc'],'Chained typeof, strict:true and ApplyGlobalResponse status-keyed json maps supported; onError and global middleware not inferred automatically. Type exports/OpenAPI do not validate runtime.','none','Compile success and known error unions from an actual client import; omitted branch must fail type expectation.'),
'errors-logs':(['hono-api-exception','hono-api-hono','hono-middleware-builtin-logger'],'HTTPException.getResponse does not import Context headers; onError is an error hook; logger does not supply project redaction/status policy.','none','An actual thrown HTTPException drops accepted Context headers or changes the existing unknown-error envelope.'),
'framework-currency':(['hono-release','hono-migration','hono-node-release','node-adapter-package','cf-compat-flags'],'Version-first method is sound; live Node guide still advertises older Node floor while stable adapter v2.1.1 requires Node >=20. CF flags now have a date-dependent default.','Add concrete dated compatibility branch; never upgrade installed runtime implicitly.','Resolve Node18+adapter2 as incompatible; preserve an independently verified older adapter branch.'),
'high-risk-backend-contract':([], 'Local HRB ownership contract, not a Hono product API. HTTP contribution remains separate from database/domain/spec/security evidence.','none','An HTTP-only test is presented as direct RLS/RPC or durable-delivery proof.'),
'observability':([], 'Conditional project-owned logging, metrics, telemetry and live debugging obligations; no platform API/default asserted.','none','Agent creates an unrequested telemetry endpoint or treats configuration as operational readback.'),
'perf-security':(['hono-middleware-builtin-body-limit','hono-middleware-builtin-timeout','hono-middleware-builtin-compress','hono-concepts-routers','hono-middleware-builtin-secure-headers','hono-middleware-builtin-cors'],'bodyLimit and timeout supported; timeout does not fit streaming. CF Workers/Deno Deploy compression guidance and Bun body bound require runtime distinction. Presets/router choice does not prove performance.','none','Oversize request bypasses selected bound, timeout breaks stream, or compression is attributed to unobserved adapter.'),
'pipelines':(['hono-guides-middleware','hono-api-hono','hono-guides-validation','hono-middleware-builtin-cors','hono-middleware-builtin-secure-headers'],'Registration order and onion execution matter; hooks not middleware positions; provider signature raw-body order stays producer-owned.','none','Real request demonstrates changed admission, missing error headers, or body consumed before signature verification.'),
'rate-limiting':(['cf-runtime-apis-bindings-rate-limit'],'Workers rate limit binding is local/eventually consistent and unsuitable for exact accounting. Actor/key scope and WAF choices stay owner-supplied.','none','Location-local limiter accepted as exact cross-region financial/quota counter.'),
'routers':(['hono-concepts-routers'],'SmartRouter/RegExpRouter/TrieRouter/LinearRouter/PatternRouter and default selection documented. Route-set constraints and measurement required before overriding.','none','Selected router fails project route syntax or assumed benchmark replaces measured workload.'),
'security':(['cf-runtime-apis-web-crypto','hono-middleware-builtin-secure-headers','hono-middleware-builtin-cors'],'Runtime primitives/features exist, but policy and exploitability belong to security/platform owner; no fixed WAF/Turnstile policy asserted.','none','Platform feature name is treated as complete authorization or a new policy is imposed.'),
'supabase':(['supabase-getting-started-api-keys','supabase-database-postgres-row-level-security','sdk-package'],'Request-scoped user client preserves JWT/RLS; elevated backend isolation required. Hono response evidence cannot close Data API boundary. SDK stable Node >=22 raises joint adapter/runtime floor for Node integration.','Record installed SDK/adapter/runtime matrix when Node is targeted.','Request user A reads B rows or Hono tests substitute for direct JWT/RLS calls.'),
'typing':(['hono-api-context','hono-helpers-factory'],'Bindings/Variables generics, createMiddleware and conditional ContextVariableMap augmentation supported; global augmentation does not initialize request values.','none','Route reads absent Context state despite type assertion or scoped state leaks across requests.'),
'validation-openapi':(['hono-guides-validation','hono-guides-rpc','zod-validator-readme','zod-validator-package'],'validator/zValidator, c.req.valid, content-type empty-object behavior, lowercase header keys and multiple validator composition supported. OpenAPI chosen only where contract needs it. Runtime response validation requires executing code.','none','Missing/wrong content type passes required validation; compile/schema presence is called response-path validation.'),
'workers-platform':(['cf-platform-limits','cf-runtime-apis-context','cf-languages-typescript-index','cf-runtime-apis-web-crypto','hono-getting-started-cloudflare-workers'],'Workers CPU/wall/subrequest/memory/lifecycle distinctions and bindings supported; waitUntil shared post-response window is bounded and non-durable; limits are retrieved per plan/environment.','none','waitUntil is claimed durable or Node/process APIs are assumed without actual compatibility mode.'),
'wrangler':(['cf-wrangler-configuration','cf-wrangler-environments','cf-languages-typescript-index','cf-runtime-apis-nodejs-index','cf-compat-flags','workerd-compat'],'Generated types and non-inheritable environment bindings/vars are supported; nodejs_compat instruction lacks new 2026-08-04 default.','H02','Compare effective compatibility before and after 2026-08-04, including both negative flags.')}
S={
'architecture':([], 'Supabase supplies platform constraints; general topology/decomposition remains architecture-engineer-owned. No DAU-only architecture selection.','none','Agent invents topology or blocks an adequate existing design on hypothetical scale.'),
'auth':(['sdk-auth-source','supabase-auth-server-side-advanced-guide','supabase-auth-jwts','supabase-auth-sessions','supabase-auth-managing-user-data'],'getClaims verifies identity; getUser obtains fresh server state; getSession user object untrusted. app_metadata trusted only with freshness constraints; user_metadata user-editable. auth.users not exposed Data API; profiles FK valid.','none','getSession user object authorizes protected data or editable metadata grants a role.'),
'client-setup':(['supabase-auth-server-side-creating-a-client','supabase-auth-server-side-advanced-guide','ssr-types','ssr-cookies','ssr-changelog','supabase-getting-started-api-keys','supabase-auth-server-side-migrating-to-ssr-from-auth-helpers'],'Current SSR getAll/setAll supported and old get/set/remove deprecated. Current callback supplies cache headers; request+response cookie propagation required. Key channel and JWT are distinct; elevated header can be replaced by signed-in user JWT.','Clarify callback headers version branch (SSR >=0.10); old supported projects must not be silently upgraded. Explain effective Authorization identity when discussing bypass.','Capture real SSR Set-Cookie/cache headers, and separate user/elevated clients; installed old SSR must stay compatible.'),
'data-handling':([], 'PII discovery, redaction and accepted retention are integration policy; no independent GDPR/legal assertion. Regulatory conclusions stay gdpr-compliance-owned.','none','Logs leak fixture credentials or retention job deletes data without an accepted contract.'),
'database':(['sdk-postgrest-source','sdk-builder','supabase-database-joins-and-nesting','pg-sql-select'],'CRUD/select/filter/order/single/maybeSingle/count/head/RPC shapes supported. Cursor uses non-unique created_at and may omit tied rows. Several snippets ignore returned errors.','S02,S04','51 equal timestamps with page size50 must all be returned exactly once; deny/error must remain distinct from no rows.'),
'db-functions':(['supabase-database-functions','supabase-database-postgres-triggers','pg-function','pg-retry','pg-errors'],'SQL/PLpgSQL functions, trigger NEW/return NEW, SECURITY INVOKER/default PUBLIC EXECUTE/search_path/schema qualification supported. Genuine 40001/40P01 whole-transaction retry distinct from application outcomes; immutability must reflect actual effects.','none','Replayed effective function spoofs domain conflict as40001, loses same-transaction audit or exposes definer to unwanted role.'),
'edge-functions':(['supabase-functions-auth','supabase-functions-auth-headers','supabase-functions-dependencies','supabase-functions-background-tasks','supabase-functions-ephemeral-storage','supabase-functions-limits'],'Deno.serve/npm:/node:/tmp and bounded waitUntil supported. Current verify_jwt accepts legacy/asymmetric JWT and may pass opaque API keys without authenticating caller; current official server adapter offers explicit auth modes.','Add dated concrete auth behavior and explicit handler auth; do not infer caller authentication from gateway pass.','Direct requests with public key/userJWT/secret/no credential prove selected auth mode; local success does not close cloud gateway.'),
'high-risk-backend-contract':([], 'Local HRB contract assigns durable transaction, RLS/RPC, audit, concurrency and lifecycle gates to Supabase; HRB08 response taxonomy stays HTTP-owner.','none','One route or mocked DB response closes an unobserved RLS or concurrent transaction boundary.'),
'migrations-cli':(['cli-release','cli-diff-doc','cli-declarative-sync-doc','cli-declarative-generate-doc','cli-diff-command','cli-diff-handler','cli-generate-command','supabase-cli-getting-started','supabase-local-development-declarative-database-schemas'],'CLI2.117 stable help/pinned docs: db diff compares migration shadow/live DB, excludes declarative files; declarative sync experimental generates migration from files. Live guide still describes older db diff path. Imperative migration new/up/reset commands exist.','S01','Change only declarative file and prove generated migration contains delta; ordinary dbdiff on pinned CLI is not that proof.'),
'operations-observability':([], 'Metrics, trace fields and health endpoint are architectural/HTTP contract choices. Baseline mandates new /health and blanket backoff/queueing despite root and reliability scope rules.','S05','Narrow diagnostic task introduces public health endpoint/queue or retries a write without accepted idempotency.'),
'operations-release':(['supabase-cli-getting-started','supabase-js-release'],'Upgrade changelog/test workflow is valid when upgrade authorized. Dedicated cloud project, split environments and health alerts are unconditionally imposed despite accepted topology ownership. Load/cost changes otherwise properly conditional.','S05','Local-only CI task creates external project or new service; narrow fix upgrades SDK without authorization.'),
'operations-reliability':(['pg-retry','sdk-builder','sdk-retry','sdk-retry-common','sdk-postgrest-client','supabase-api-automatic-retries-in-supabase-js','supabase-database-connecting-to-postgres'],'Application retry/idempotency/bounded budgets are sound but current SDK has default retry policy. Pinned v2.116 source retries GET/HEAD/OPTIONS for503/520/network max3 retries; live page advertises a different broader contract. Pool mode/prepared statement compatibility verified.','S06','Injected transient failure counts actual transport calls against whole-operation budget including SDK retries.'),
'realtime':(['supabase-realtime-subscribing-to-database-changes','supabase-realtime-authorization','supabase-realtime-postgres-changes','supabase-realtime-presence'],'Broadcast/private realtime.messages policies, Presence ephemeral state and Postgres Changes publication/grants/JWT/RLS supported. Authorization cached at channel join/newJWT; DELETE not filterable and RLS cannot check deleted row, old full payload still restricted to PK under RLS.','Add concrete lifecycle/delete limits when relevant; do not present generic post-change RLS as all-event guarantee.','Permission changes and delete events exercised on actual subscription, including reconnect and cleanup.'),
'rls':(['supabase-database-postgres-row-level-security','supabase-storage-security-access-control','supabase-api-securing-your-api','supabase-auth-managing-user-data'],'RLS/grants, auth.uid initplan, roles, USING/WITH CHECK, UPDATE SELECT policy, invoker views PG>=15, BYPASSRLS vs FORCE, trusted metadata and auth.users FK supported. Storage public select policy permits listing as well as reads unless operation narrowed.','Keep views PG>=15 explicit and example ownership conditional; operation-specific SELECT matters if list visibility differs.','Direct userJWT allow/deny queries, tied actor scopes, invoker views, grants and Storage list/download/upsert are independently exercised.'),
'security-privileges':(['supabase-api-securing-your-api','supabase-database-postgres-roles','supabase-database-functions','supabase-getting-started-api-keys'],'GRANT schema/table/sequence/function, role-switch distinction, default PUBLIC EXECUTE and elevated isolation supported; inspect real existing grants rather than assume new defaults.','none','Policy exists but actual direct role cannot operate or an unintended role retains EXECUTE/SELECT.'),
'storage':(['sdk-storage-source','supabase-storage-security-access-control','supabase-storage-uploads-standard-uploads','supabase-storage-serving-downloads'],'upload/upsert/getPublicUrl/createSignedUrl/remove/list supported. getPublicUrl is synchronous URL construction for public bucket, not reachability proof. Signed result may contain data:null,error; baseline nested destructuring crashes.','S04','Denied/nonexistent signed URL yields controlled error, not TypeError; real public/private download and replacement checked separately.'),
'troubleshooting':(['supabase-getting-started-api-keys','supabase-functions-auth','supabase-api-handling-errors-in-supabase-js','sdk-builder','supabase-database-postgres-row-level-security','supabase-database-connecting-to-postgres'],'Error taxonomy and verify-original-failure path sound: keys/JWT,42501 grants+RLS,empty updates, cardinality116,retrybudget,pool compatibility. Incident-specific codes/settings remain environment evidence.','none','Agent broadens privileges or declares success from 2xx/no affected row.'),
'vector':(['supabase-ai-vector-columns','supabase-ai-semantic-search','supabase-ai-vector-indexes','supabase-ai-vector-indexes-hnsw-indexes','supabase-ai-vector-indexes-ivf-indexes','pgvector'],'vector/cosine_ops/<=>/ascending distance and RPC shape valid; fixed dimension/threshold are example assumptions. IVFFlat on newly empty table with arbitrary lists100 conflicts with training/data prerequisite and current generally preferred HNSW guidance.','S03,S04','Cold-table ANN build followed by dataset compare to exact search must meet accepted recall; dimensions follow embedding producer.'),
'webhooks':(['supabase-database-webhooks','supabase-database-extensions-pg_net','supabase-database-vault','supabase-auth-auth-hooks','supabase-auth-auth-hooks-send-email-hook','standardwebhooks-spec'],'Database Webhooks pg_net asynchronous payload/history, no universal signature; Auth StandardWebhooks rawbody/base64/multiple signatures and bidirectional time tolerance supported. Auth-specific timeout/retry differs from generic webhook recommendations.','none','Valid raw signature passes; mutation/old/future/wrongkey fails; duplicate does not duplicate durable effects; replaycurl is only routing evidence.')}
# Corrections identify tight original source ranges and separately list objective evidence.
findings=[
('H01','hono-engineer','references/auth.md',11,12,'Bearer 400 относится к входящему Authorization, а не к конфигурации','Hono4.13.7 parses the request header and rejects malformed format with400. options.token is compared later; missing token/verifyToken throws during construction.','hono-bearer-source','154-214;107-109','Differentiate malformed request400, credential mismatch401 and configuration construction failure; show anchored regex only if needed.','No auth bypass demonstrated; confirmed wrong diagnostic/status oracle is P2.'),
('H02','hono-engineer','references/wrangler.md',10,10,'nodejs_compat больше не всегда opt-in','Compatibility dates >=2026-08-04 enable both Node flags by default; disabling requires both negative flags and removal of positive flags. Older dates retain version-specific opt-in.','cf-compat-flags','62-91','Use date-aware effective compatibility, with old-project branch; do not move compatibility_date automatically.','No exploit or unauthorized platform mutation demonstrated; wrong configuration guidance is P2.'),
('S01','supabase-engineer','references/migrations-cli.md',9,14,'Declarative db diff путь не соответствует CLI2.117','Pinned CLI docs and read-only help distinguish ordinary shadow/live diff from experimental db schema declarative sync. Live website is stale relative to pinned CLI behavior.','cli-diff-doc','1-40','Inspect installed help; use supported declarative sync only with explicit experimental status, or keep older verified CLI branch. Do not switch migration model.','No production mutation performed; migration can omit intended changes, a P2 contract failure.'),
('S02','supabase-engineer','references/database.md',43,52,'Курсор created_at теряет строки с одинаковым timestamp','After returning50 of51 rows with identical created_at, gt(created_at,cursor) excludes the51st forever. No unique timestamp invariant is declared.','pg-sql-select','ORDER BY/LIMIT sections','Use a unique total ordering and tuple cursor, or explicitly establish unique key invariant; keep returned error handling.','Deterministic data omission in example is P2; no production loss claimed.'),
('S03','supabase-engineer','references/vector.md',3,16,'IVFFlat создаётся до данных без измерения параметров','Official pgvector/Supabase guidance requires representative data before IVFFlat build; empty/small training set reduces returned results. lists100 is not justified for this new empty table.','pgvector','334-342;939-941','Use measured exact/HNSW baseline or defer IVFFlat until adequate data, derive dimension/index params from accepted workload, check recall.','Confirmed setup/retrieval correctness risk is P2; no actual application vector workload observed.'),
('S04','supabase-engineer','references/storage.md',20,24,'Примеры пропускают nullable data/error контракт SDK','createSignedUrl failure returns data:null plus error; nested signedUrl destructuring throws TypeError. Database/RPC/remove/list examples also omit returned errors, conflicting with root rule.','sdk-storage-source','createSignedUrl','Check error before data; update all related async examples consistently, leaving synchronous getPublicUrl shape accurate.','Local example failure is P2; no secret disclosure or irreversible external effect demonstrated.'),
('S05','supabase-engineer','references/operations-observability.md',3,12,'Operations reference навязывает новый HTTP/топологический контракт','Expose /health, counters/traces and blanket429 queue/backoff are unconditional; release mandates dedicated CI project/separate projects/health despite root preserving topology and reliability requiring measured failure/idempotency.','LOCAL','fragments/overview.md:15-31;references/architecture.md:24-28;references/operations-reliability.md:3-18,26-28','Condition observability/release recommendations on accepted project contract and measured need; keep HTTP/topology owners and bounded idempotent retry rules.','P2 source-to-action conflict; exploit, actual scope expansion and production effects not observed.'),
('S06','supabase-engineer','references/operations-reliability.md',3,18,'Retry budget не учитывает включённые повторы текущего SDK','Pinned2.116 PostgREST builder uses default retry:true: GET/HEAD/OPTIONS transient transport failures can produce4 attempts before caller helper repeats. Current live doc describes a different retry set, so use pinned implementation for exact version.','sdk-retry','fetchWithRetry plus types/common/common.ts','Inspect effective installed retry policy, budget all transport attempts; db.retry:false or query.retry(false) when accepted caller policy must own budget. Do not assert POST retry from conflicting live page.','Extra attempts/deadline violation possible in existing owned retry task; P2, no non-idempotent POST duplication claimed.')]
# Helper emits comprehensive leaf blocks: every nonblank active reference line is covered by a location; fenced code is a single atomic block.
def blocks(lines):
 out=[];i=0;title='Introduction'
 while i<len(lines):
  if not lines[i].strip():i+=1;continue
  if lines[i].startswith('#'):
   title=lines[i].lstrip('# ').strip();out.append((i+1,i+1,title,'heading'));i+=1;continue
  a=i
  if lines[i].startswith('```'):
   i+=1
   while i<len(lines) and not lines[i].startswith('```'):i+=1
   i=min(i+1,len(lines));kind='code-example'
  elif lines[i].startswith('|'):
   while i<len(lines) and lines[i].startswith('|'):i+=1
   kind='contract-table'
  else:
   i+=1
   while i<len(lines) and lines[i].strip() and not lines[i].startswith(('#','```','|','- ')):i+=1
   kind='instruction-or-claim'
  out.append((a+1,i,title,kind))
 return out
for skill,mapping in [('hono-engineer',H),('supabase-engineer',S)]:
 root=W/'skills'/skill;rows=[];active=[]
 for f in sorted((root/'references').glob('*.md')):
  keys,conclusion,delta,falsifier=mapping[f.stem]
  for a,b,title,kind in blocks(f.read_text().splitlines()):
   applicable=[x[0] for x in findings if x[1]==skill and x[2]=='references/'+f.name and not (b<x[3] or a>x[4])]
   if skill=='supabase-engineer' and f.stem=='database' and kind=='code-example':applicable=list(dict.fromkeys(applicable+['S04']))
   if skill=='supabase-engineer' and f.stem=='vector' and title=='Usage' and kind=='code-example':applicable=['S04']
   if skill=='supabase-engineer' and f.stem=='operations-release' and title in ['CI integration','Multi-environment setup','Deploy checklist (minimum)']:applicable=['S05']
   if skill=='supabase-engineer' and f.stem=='operations-observability' and a>=21:applicable=['S05']
   status='correction-required' if applicable else 'verified' if keys and kind!='heading' else 'N/A'
   reason='Heading/navigation, no technical proposition.' if kind=='heading' else 'Local authority/evidence/ownership instruction, not a vendor API/default; evaluated for consistency with repository and stable owner contracts.' if not keys else None
   sourceitems=[{'id':k,'url':cat[k]['url'],'snapshot':cat[k]['snapshot'],'retrievedAt':cat[k]['retrievedAt'],'sha256':cat[k]['sha256Readback']} for k in keys]
   row={'id':f'{skill}-{len(rows)+1:03}','aspect':title,'kind':kind,'location':{'file':str(f.relative_to(W)),'lines':[a,b]},'version':'Hono4.13.7 stable; adapter2.1.1 stable; Workers rolling compatibility-date contract' if skill.startswith('hono') else 'supabase-js2.116.0, SSR0.12.7, CLI2.117.0 stable; hosted docs rolling; PostgreSQL deployment version must be inspected','sources':sourceitems,'result':status,'reason':reason,'verification':conclusion,'necessaryChange':'; '.join(applicable) if applicable else delta,'falsifier':falsifier,'evidenceBoundary':'Official source/static consistency only; no fresh agent behavioral trial or deployed runtime proof.'}
   rows.append(row)
  active.append(str(f.relative_to(W)))
 # Source/emitted root provenance for each line; source yaml sections also independently inventoried.
 emitted=(root/'SKILL.md').read_text().splitlines()
 for rel in ['fragments/overview.md','skill.yaml','SKILL.md','agents/openai.yaml','AGENTS.md']:
  f=root/rel;ls=f.read_text().splitlines()
  for a,b,title,kind in blocks(ls):
   text='\n'.join(ls[a-1:b]);matches=[]
   if rel=='fragments/overview.md':
    for i in range(len(emitted)-b+a):
     if emitted[i:i+b-a+1]==ls[a-1:b]:matches.append({'file':f'skills/{skill}/SKILL.md','lines':[i+1,i+b-a+1]})
   rows.append({'id':f'{skill}-{len(rows)+1:03}','aspect':title if rel.endswith('.md') else rel+' source fields','kind':kind,'location':{'file':str(f.relative_to(W)),'lines':[a,b]},'emittedMatches':matches,'version':'skill0.1.7' if skill.startswith('hono') else 'skill0.1.6','sources':[],'result':'N/A','reason':'Repository instruction contract/metadata or duplicate generated surface, not independent vendor authority. Technical claims cross-referenced to full reference inventory; source/emitted snapshot preserved.','verification':'Read full source bundle and generated root; reference loading, modes, ownership, stops and evidence boundaries assessed against standard and stable direct owners.','necessaryChange':'Propagate applicable finding consistently through source and regenerate; no generated-only fix.','falsifier':'Regenerated root omits source condition, references missing, selection differs from claimed trigger, or instruction forces authority/ownership drift.','evidenceBoundary':'Static source and generated comparison; activation/execution trials pending.'})
 inv=[]
 for f in sorted(root.rglob('*')):
  if not f.is_file():continue
  rel=str(f.relative_to(root)); role='active reference/source' if rel.startswith(('references/','fragments/')) or rel in ['skill.yaml','SKILL.md','agents/openai.yaml'] else 'maintenance guidance' if rel=='AGENTS.md' else 'structural-only test/package' if rel.startswith('test/') or rel=='package.json' else 'supporting historical evidence/navigation'
  inv.append({'file':str(f.relative_to(W)),'sha256':sha(f),'bytes':f.stat().st_size,'role':role,'review':'Full current active read and reference map' if 'active' in role else 'Inventoried; selected declared logs/compile-report/docs navigation read; no historical behavioral PASS reused' if 'supporting' in role else 'Read; structural tests do not invoke Hono/runtime/Supabase services'})
 report={'skill':skill,'auditKind':'independent baseline, full active technical inventory','snapshot':{'baseCommit':'d89d66f2c99bf8b9e84e5b4def54fa60192856a5','packageVersion':'0.1.7' if skill.startswith('hono') else '0.1.6','rootSha256':sha(root/'SKILL.md'),'baselineReadback':'hono-supabase-baseline-readback.json'},'checkedAt':'2026-09-09','officialSourceCatalog':'official-hono-supabase-sources.json','findings':[x[0] for x in findings if x[1]==skill],'boundaries':{'sourceCoverage':'All active references, complete YAML, fragment, generated root, UI and maintenance declaration inventoried; each nonblank reference line mapped.','notClaimed':['Fresh GPT-6 Astra behavioral performance','Runtime Hono or Supabase API behavior from this audit','Cloud deploy, Realtime delivery, Auth server, Storage, Edge runtime, operating-system or production correctness','Historical logs as current evidence'],'structuralChecks':'Baseline hash readback only by reviewer; Hono package test and repository mandatory gates owned by parent','runtimeChecks':'Supabase CLI2.117.0 read-only version/help probes only; no local/remote DB mutation performed by reviewer','sourceConflicts':['CLI live declarative guide vs stable2.117 pinned help: exact installed CLI branch wins.','Supabase automatic retry live page vs stable2.116 implementation: pin observed source policy, do not copy unsupported POST retries.','Hono live Node guide legacy floor vs adapter2.1.1 engine>=20: exact adapter package constrains runtime.']},'inventory':inv,'coverage':rows}
 (E/('technical-hono.json' if skill.startswith('hono') else 'technical-supabase.json')).write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
(E/'hono-supabase-findings.json').write_text(json.dumps([dict(zip(['id','skill','file','start','end','title','evidence','officialSource','officialLocation','resolution','p1Screen'],x)) for x in findings],ensure_ascii=False,indent=2)+'\n')
print('written',len(cat),'official snapshots;',len(H),'Hono references;',len(S),'Supabase references')
# Normalize repeated source metadata and combine contiguous claims/examples within a named section.
for short,skill,mapping in [('hono','hono-engineer',H),('supabase','supabase-engineer',S)]:
 p=E/f'technical-{short}.json';d=json.loads(p.read_text());old=d.pop('coverage');groups={}
 for r in old:
  loc=r['location'];f=loc['file']
  if '/references/' not in f:continue
  key=(f,r['aspect'])
  if key not in groups:
   groups[key]={'aspect':r['aspect'],'location':loc.copy(),'versions':r['version'],'officialSources':[s['id'] for s in r['sources']],'result':r['result'],'verification':r['verification'],'necessaryChange':r['necessaryChange'],'falsifier':r['falsifier'],'kinds':[]}
  g=groups[key];g['location']['lines']=[min(g['location']['lines'][0],loc['lines'][0]),max(g['location']['lines'][1],loc['lines'][1])];g['kinds']=list(dict.fromkeys(g['kinds']+[r['kind']]))
  if r['result']=='correction-required':g['result']='correction-required';g['necessaryChange']=','.join(sorted(set(re.split(r'[,;]\s*',g['necessaryChange'])+re.split(r'[,;]\s*',r['necessaryChange']))))
  elif r['result']=='verified' and g['result']=='N/A':g['result']='verified'
  if g['result']=='N/A':g['reason']='Local ownership/authority/evidence rule or heading, not independent vendor API/default; evaluated against stable direct owners.'
 for g in groups.values():
  if g['result']!='N/A':g.pop('reason',None)
  g['necessaryChange']=g['necessaryChange'].replace('none,','').replace(',none','')
 coverage=list(groups.values())
 root=W/'skills'/skill
 for rel in ['fragments/overview.md','skill.yaml','SKILL.md','agents/openai.yaml','AGENTS.md']:
  f=root/rel;ls=f.read_text().splitlines();parity=[]
  if rel=='fragments/overview.md':
   generated=(root/'SKILL.md').read_text().splitlines()
   for i in range(len(generated)-len(ls)+1):
    if generated[i:i+len(ls)]==ls:parity=[i+1,i+len(ls)];break
  coverage.append({'aspect':rel+' complete surface','location':{'file':str(f.relative_to(W)),'lines':[1,len(ls)]},'versions':d['snapshot']['packageVersion'],'result':'verified','officialSources':[],'verification':'Read complete source, mode/trigger/reference/interop/output contract; vendor assertions duplicate aspects in references above and inherit their result, including correction-required findings. This row verifies source coverage/parity, not blanket technical correctness.','technicalClaimsResult':'See complete reference aspect map and findings; no independent current claim for duplicate root/YAML.','emittedFragmentLines':parity or None,'necessaryChange':'Propagate confirmed technical corrections through source and regenerate. Metadata/UI contain no independent vendor command.','falsifier':'Source/emitted drift, missing active reference, conflicting mode/owner/output contract, or unrequested behavior in future blind run.'})
 d['coverage']=coverage;ids=set(k for r in coverage for k in r.get('officialSources',[]));d['officialSources']={k:{'url':cat[k]['url'],'snapshot':cat[k]['snapshot'],'retrievedAt':cat[k]['retrievedAt'],'sha256':cat[k]['sha256Readback']} for k in sorted(ids)};d['coverageNote']='Each reference section maps its assertions and included code/examples to dated official source IDs resolved in officialSources. Contiguous location includes headings; local owner/evidence rules are N/A for vendor verification. Root/vendor duplicates inherit reference findings, not a separate technical PASS.'
 d['activeCoverageCounts']={'references':len(mapping),'aspects':len(coverage),'sourceEmittedUiMaintenanceSurfaces':5}
 p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
print('normalized compact coverage')
