"""Supporting inventory generator; no target-package mutations or runtime claims."""
from pathlib import Path
import hashlib, json, re

E = Path(__file__).parent
BASE = 'd89d66f2c99bf8b9e84e5b4def54fa60192856a5'
SOURCES = json.loads((E / 'official-next-electron-docusaurus-sources.json').read_text())
BY_ID = {int(Path(s['file']).name.split('-')[0]): s for s in SOURCES if s.get('file')}
DATA = {}

def add(skill, id, aspect, files, source_ids, status, basis, change='', version=None):
    DATA.setdefault(skill, []).append(dict(id=id, aspect=aspect, source_files=files.split(','), official_source_ids=source_ids, result=status, basis=basis, required_change=change or 'Сохранить; точное выполнение зависит от установленной версии и задачи.', version=version))

N='nextjs'
add(N,'N01','Stable/runtime/React/TypeScript support, existing-project version branch','fragments/overview.md,skill.yaml,SKILL.md',[0,1,2,76,340,342,343],'correction-required','Stable16.3.4; Next16 requires Node>=20.9 and TS>=5.1; React canary integration in App Router is framework-managed. Next15 remains a distinct supported branch.','Добавить installed-version/source precedence; не требовать upgrade; для нового проекта совместимый поддерживаемый Node LTS.', 'Next16.3.4 stable;15 maintenance; React19.2; Node24 LTS')
add(N,'N02','App Router files: page/layout/template/loading/error/not-found/default, route groups and special folders','references/file-conventions.md,references/app-router-files.md',[3,4,30,31,203],'verified','Имена page/layout/template/loading/error/default, dynamic/catch-all/groups/private folders и special files соответствуют App Router. Template remounts, layout preserves state; global-error replaces root layout.')
add(N,'N03','Proxy config export, matcher, middleware migration and runtime','references/file-conventions.md',[0,26,333],'correction-required','Proxy matches export const config; proxyConfig не является контрактом matcher. middleware→proxy scoped codemod существует; proxy использует Node runtime, не Edge.','Заменить proxyConfig на config, указать Node runtime и middleware-to-proxy codemod при разрешённой миграции; сохранить15 branch.')
add(N,'N04','Renderable data example and metadata route runtime','references/app-router-files.md',[6,32,61],'correction-required','fetch возвращает Response, который нельзя вставлять как React child. ImageResponse route по default Node runtime.','В примере выполнить response.json()/text() и вернуть renderable data; исправить OG Edge default.')
add(N,'N05','Async request APIs: params/searchParams/cookies/headers/draftMode/use() and codemod','references/async-patterns.md,references/metadata.md',[0,1,48,49,50,55,56,80],'correction-required','Next15 ввёл async request APIs; Next16 удалил synchronous compatibility. Основная async-patterns ветка соответствует, но viewport example обращается к params синхронно.','Согласовать все examples: await request APIs/params, React.use для sync client; не применять механически к generateImageMetadata input.')
add(N,'N06','React server/client serialization and Date/Map/Set/functions/classes','references/rsc-boundaries.md,fragments/overview.md,SKILL.md',[5,77,78],'correction-required','React RSC serializable включает Date, Map, Set, bigint, typed arrays, global Symbols, Promise, JSX и server functions; это шире JSON. Обычные функции и произвольные class instances не допускаются.','Удалить JSON-only и Date/Map/Set forbidden во всех поверхностях; сохранить исходный публичный контракт и корректные отрицательные примеры.')
add(N,'N07','Client async prohibition, server-only data, composition through children','references/rsc-boundaries.md,references/directives.md',[5,77,78,338],'verified','Async Client Components запрещены; use client формирует boundary; server-rendered JSX можно передать children; use server помечает server functions. Directive placement и module-level exported async constraints подтверждены.')
add(N,'N08','Server Actions reachability, authentication, authorization and input validation','references/data-patterns.md,references/directives.md',[7,17,78],'correction-required','Server Actions доступны прямым POST, а не internal-only. create/delete examples пишут в DB без authentication/ownership/validation. Action IDs и UI guards не authority.','Убрать internal/no-external-access; каждую mutation проверять внутри action; route/action examples должны принимать untrusted input и не считать page/proxy guard достаточным.')
add(N,'N09','Data fetching, route handlers vs actions, parallel fetch, use/Suspense and deduplication','references/data-patterns.md,references/route-handlers.md',[6,7,11,29,79,80],'verified','Server reads не требуют self-fetch через Route Handler; actions для mutations; Promise.all parallelism и React.cache request memoization различаются от persistent cache. GET handler не cache по default с15.')
add(N,'N10','revalidateTag/updateTag/revalidatePath and cache intent','references/data-patterns.md,references/directives.md',[8,24,25,62,63,64,67],'correction-required','Одноаргументный revalidateTag deprecated; profile max даёт SWR, updateTag только action и read-your-writes. cacheComponents opt-in stable16 меняет модель; use cache не должен включать request-time APIs в cached scope.','Убрать deprecated основной путь, импортировать cache APIs, выбрать updateTag/max по UX; отделить legacy cache от Cache Components.')
add(N,'N11','Route Handler methods, params/body/cookies/status, page conflict','references/route-handlers.md',[11,29,48,59,60],'verified','GET/POST/PUT/PATCH/DELETE/HEAD/OPTIONS, Response/NextResponse, async params, auto OPTIONS, body request.json и запрет route+page одного segment подтверждены. Input validation/auth остаются task-owned, не покрываются типами.')
add(N,'N12','Node vs Edge APIs, dependency compatibility and deployment-dependent latency','references/runtime-selection.md',[18,75,76],'correction-required','Node default; Edge не поддерживает native Node APIs/ISR и ограничивает dynamic code. Меньший cold-start не универсальная гарантия runtime.','Уточнить Edge restrictions, убрать безусловное smaller cold start; проверять adapter/runtime вместо географического обещания.')
add(N,'N13','Turbopack defaults, webpack preservation, server external packages and transpilation','references/bundling.md',[0,13,68,69,204],'correction-required','Turbopack default dev/build с16, а не15. serverExternalPackages/transpilePackages существуют; ESM сам по себе не требует transpilation. Старый webpack migration URL — soft404.','Исправить16default; сохранять webpack если нужен; package claims проверять по конкретной dependency; заменить stale URL.')
add(N,'N14','Browser-only dynamic import, ssr:false, client wrapper and CSS','references/bundling.md',[5,10,12],'correction-required','ssr:false недоступен внутри Server Component. use client само по себе сохраняет SSR начального HTML. Official lazy-loading требует client wrapper вокруг dynamic ssr:false.','Исправить пример и объяснение wrapper; production import/build/SSR probe для window-at-import library.')
add(N,'N15','Navigation hooks, Link, params/segments/reportWebVitals','references/functions.md',[40,41,42,43,44,45,46,47],'correction-required','useRouter/usePathname/useSearchParams/useParams/selected segments и web vitals подтверждены. useLinkStatus возвращает navigation pending, только внутри Link, не общий prefetch status.','Исправить useLinkStatus и его import next/link; Link default не запрещает intentional native anchor navigation.')
add(N,'N16','Server helpers after/connection/userAgent and request-response classes','references/functions.md',[48,49,50,51,52,53,54,59,60,61],'verified','Async cookies/headers/draftMode; after next/server executes post-response but within host duration, connection next/server defers to request; userAgent, NextRequest/NextResponse/ImageResponse imports и generateStaticParams purpose подтверждены.')
add(N,'N17','Suspense conditions, static production search and pathname','references/suspense-boundaries.md',[40,41,52,337],'correction-required','Static useSearchParams без ближайшего Suspense проваливает production build; dev может скрывать. usePathname Suspense зависит от cacheComponents и unknown dynamic params.','Заменить blanket CSR и все dynamic routes на точные conditions; проверять production build, не только dev.')
add(N,'N18','Hydration causes, useEffect/useId/suppressHydrationWarning and client-only island','references/hydration-error.md',[5,12,81,339],'verified','Deterministic initial output, invalid HTML, browser globals, browser extension/date mismatch; useEffect client difference, scoped suppressHydrationWarning, dynamic client-only подходы подтверждены. Suppression не исправляет root cause.')
add(N,'N19','Error boundaries, reset/global-error and Next control-flow exceptions','references/error-handling.md',[9,31,34,35,36,39],'correction-required','error/global-error требуют client boundary; redirect throws, catch by message NEXT_REDIRECT ненадёжен. redirect обычно307, в Action303; streamed notFound можетHTTP200. unstable_rethrow API explicitly unstable/not production-recommended.','Убрать message equality; вынести redirect outside catch либо version-appropriate rethrow, пометить unstable branch и реальные status boundaries.')
add(N,'N20','forbidden/unauthorized experimental authInterrupts','references/error-handling.md',[37,38,336],'correction-required','forbidden/unauthorized экспериментальны и требуют experimental.authInterrupts; official docs не рекомендуют production.','Убрать из stable default, указать gate и alternative explicit401/403 response по framework boundary.')
add(N,'N21','Metadata/static metadata/generateMetadata/viewport/OG/sitemap/robots/icons','references/metadata.md',[32,33,55,56,57,58,61],'correction-required','Image default function получает Promise params/id; generateImageMetadata params остаются sync16; sitemap id Promise<string> с16. Основные metadata exports поддержаны.','Исправить params/id/Number(await id), viewport и Node default; сохранить sync generateImageMetadata input.')
add(N,'N22','Images: sizes/fill/remotePatterns/static imports/preload/priority/quality/security defaults','references/image.md',[0,72],'correction-required','Image sizing/remotePatterns подтверждены. priority deprecated16→preload, но не всегда следует preloading; max redirects3/local-IP off/qualities75/minTTL4h и optimizer auth ограничения влияют на существующие задачи.','Убрать priority из нового пути; version-qualified preload/eager/fetchPriority; уточнить remotePatterns и size selection, не расширяя scope.')
add(N,'N23','Fonts: Google/local loading, weights/styles/subsets/preload, CSS vars and Tailwind','references/font.md',[73,331,332],'correction-required','next/font self-hosts build-downloaded Google files, browser не обращается к Google. subsets выбирают preloading, отсутствие не означает все символы. Variable fonts рекомендованы; Tailwind config example являетсяv3 веткой.','Исправить subsets/all-weights claims, показать v4 @theme inline приv4 и сохранитьv3 example; не обещать отсутствие build network.')
add(N,'N24','Scripts: loading strategies, client handlers, worker and JSON-LD','references/scripts.md',[20,21,22,74],'correction-required','beforeInteractive/afterInteractive/lazyOnload и client event handlers подтверждены; worker экспериментален, требует flag и не поддерживается App Router. JSON-LD official использует native script.','Убрать always next/script и неподписанный worker path; отличить JSON-LD sanitation, App Router support и third-party package version.')
add(N,'N25','Parallel/intercepting routes, default/null/catchall, refresh and modal history','references/parallel-routes.md',[27,28,42],'correction-required','Slots не URL segments; default on hard navigation; close via back или Link к null catchall. [... ]catchall spelling неверен; back не удаляет entry из history.','Исправить [...catchAll], Link/null close option и direct-entry history fallback; verify soft/hard navigation.')
add(N,'N26','CLI debug-build-paths and MCP dev diagnostics, upgrade codemod authority','references/debug-tricks.md',[14,15,71,334,340,341],'correction-required','debug-build-paths принимает filesystem app/.../page.tsx, не URL. Next16+ exposes MCP endpoint; before16 experimental.mcpServer universal flag не подтверждён. Новые tools version-sensitive.','Проверять local help/version/dev-server, narrow build не full proof; убрать выдуманный pre16 flag и не требовать global MCP install.')
add(N,'N27','Self-hosting start/standalone/static export/Docker/PM2/env/sharp/reverse proxy','references/self-hosting.md',[18,19,23,70,199,354],'correction-required','next start требует build; standalone server.js и public/.next/static копируются отдельно; NEXT_PUBLIC inlined build-time; static export не поддерживает server features. Docker Node20 EOL после2026-04.','Поддерживаемый совместимый Node для новых deploy, preserve existing project; отделить deployment choice/PM2 от универсального production требования.')
add(N,'N28','Distributed cache handlers, Redis/S3 examples and cross-instance invalidation','references/self-hosting.md',[18,24,65,66],'correction-required','No-op Redis revalidateTag и S3 без invalidation не реализуют заявленную общую cache solution. cacheHandler vs cacheHandlers имеют разные contracts. Multi-instance requires coordination/invalidation and consistent keys/deployment.','Не выдавать sketch за рабочую solution: убрать или явно ограничить; полноценный shared handler должен доказать invalidation across instances.')
add(N,'N29','OpenNext/platform adapter support and deployment API','references/self-hosting.md',[327,328,329,330],'correction-required','OpenNext moved to opennext.js.org; platform adapters/version/features различаются. AWS page scope15; Cloudflare page имеет stale14 timeframe и Node middleware limitation. Нельзя выводить all-platform parity.','Обновить URL, отдельно выбирать current adapter+Next supported matrix; заявления Deno/универсальной поддержки оставить unverified до exact owner source.')

EL='electron-engineer'
add(EL,'E01','Installed tool/runtime/OS release matrix and stable vs experimental','fragments/overview.md,SKILL.md,references/tooling-project-structure.md',[94,95,97,319,322,344,345,360],'correction-required','Electron44 stable меняет OS/native APIs; electron-vite5 Node^20.19||>=22.12, Vite5|6|7, SWC optional. Electron npm host engine>=22.12 отличается bundled Node.','Добавить explicit installed/stable branch, no unsolicited upgrade, Electron44 macOS>=13/64-bit targets и43 compatibility when applicable.', 'Electron44.3.0 stable;43 supported project branch; electron-vite5.0.0 stable/4 project branch; Forge7.11.2')
add(EL,'E02','Process model/lifecycle/single instance/window/session/utility ownership','references/architecture.md',[82,102,103,105,112],'verified','Main/preload/renderer/utility boundaries, ready UI, requestSingleInstanceLock, open-file/open-url/activate, WebContentsView вместо BrowserView для новых compositions соответствуют APIs. Policies о минимальных capability — design constraints.')
add(EL,'E03','Protocol scheme privileges vs handler/session registration timing','references/architecture.md',[109],'correction-required','Только registerSchemesAsPrivileged before ready; обычные protocol methods/partition session требуют ready. Широкий bootstrap bullet register protocols before whenReady конфликтует с API.','Сузить раннюю регистрацию до privileges; protocol.handle после ready и на правильной session; path traversal deny probe.')
add(EL,'E04','Sandbox/contextIsolation/nodeIntegration/webviewTag/CSP/openExternal','references/security-ipc-preload.md,references/renderer-integration.md',[83,84,85,103,106],'verified','secure BrowserWindow settings и narrow bridge соответствуют official security baseline; sandboxed preload имеет limited require, без полноценной Node environment. App content остаётся untrusted.')
add(EL,'E05','IPC handle/invoke schemas/results/sender/window/frame/session and contextBridge limits','references/security-ipc-preload.md,references/typescript-in-electron.md',[83,85,86,106,107,108],'verified','Payload checks не заменяют senderFrame authority; raw ipcRenderer нельзя exposed across contextBridge, structured cloning ограничивает prototypes/symbols/native objects. contextBridge functions proxy и frozen copied data. Narrow facade supported.')
add(EL,'E06','Navigation deprecated positional arguments and deny policy','references/security-ipc-preload.md',[83,104,97],'correction-required','Current webContents API помечает positional url deprecated и даёт details.url; security tutorial всё ещё показывает old callback. Это deprecated, не removed. will-navigate не ловит программный loadURL и same-document.','Новый sample details.url; сохранить старую version branch при необходимости, запреты проверять и на main-owned load paths; runtime probe resolving source discrepancy.')
add(EL,'E07','Session permission check/request/device/display-media and cleanup','references/security-ipc-preload.md,references/native-os-integration.md,references/testing-observability.md',[110,120],'correction-required','Для полного permission handling official требует check+request handlers. webContents в check nullable, subframes определять requestingOrigin/details. Baseline generic handler не фиксирует оба контура.','Уточнить оба handlers/nullable/frame scope и display-media когда feature затронута; deny request не доказывает deny check.')
add(EL,'E08','Electron-vite build/dev/preview/outDir/env/assets/externalization','references/build-process.md,references/tooling-project-structure.md,references/typescript-in-electron.md',[129,130,133,134,137,139,140,141,321,322],'verified','dev/build/preview, outDir, sections main/preload/renderer, prefix-scoped env, assets and runtime dependencies подтверждены. v5 prefer build.externalizeDeps, старый plugin deprecated; baseline не содержит obsolete plugin call.')
add(EL,'E09','Isolated build release channel and sandboxed preload bundling','references/build-process.md,references/tooling-project-structure.md,references/typescript-in-electron.md',[84,87,134,135],'correction-required','Full bundled CJS preload сохраняет sandbox; native ESM sandboxed preload unsupported. Isolated build официально experimental, baseline рекомендует без label.','Пометить experimental и verify installed support; использовать только при реальном shared-chunk failure, не как universal default.')
add(EL,'E10','Forge package/make/publish cascading and same-artifact evidence','references/build-process.md,references/packaging-release-updates.md',[142,315],'correction-required','make по default перепаковывает; publish запускает package+make. Baseline pipeline smoke→make→publish и prebuild scripts меняют проверенный artifact после проверки.','Freeze make artifacts, hash и verify их; publish --dry-run/--from-dry-run либо эквивалент без rebuild; --skip-package только осознанно; source build до формирования, не перед from-dry-run.')
add(EL,'E11','pnpm install layout with Forge','references/build-process.md,references/tooling-project-structure.md',[142],'correction-required','Forge package официально требует node-linker=hoisted для pnpm; default skill pnpm path не содержит настройки.','Указать локальную compatibility настройку для Forge, проверить lockfile/install/runtime layout; не менять global pnpm.')
add(EL,'E12','ASAR/native unpack/rebuild/fuses/integrity/source exposure','references/source-protection.md,references/build-process.md,references/packaging-release-updates.md,references/data-storage-native.md',[88,89,90,91,101,318],'verified','ASAR не encryption; native modules may need unpack; ABI rebuild targets Electron version/arch. Fuses/integrity ограничены platform/toolchain и требуют packaged proof. Signed bytes должны совпадать с final modified artifact.')
add(EL,'E13','Bytecode/source maps/minification/SWC/source protection and platform caveats','references/source-protection.md,references/build-process.md',[132,136,138,322],'verified','electron-vite bytecode production main/preload, not renderer; sandbox-preload conflicts; runtime-specific V8 output, arrow transform/protection limitations; private source maps и no-secret client guarantees correctly bounded. v5 build.bytecode replaces deprecated plugin when exact config is introduced.')
add(EL,'E14','Signing/notarization/timestamp/CI makers and update channel/provenance','references/packaging-release-updates.md',[92,93,101,113,143,146,147,315,316,317],'verified','mac signing/notarization and Windows signing are distinct target lanes; Forge package may sign/notarize before make. Linux built-in autoUpdater unavailable; target maker/update strategy determines support; local fake feed is not production update installation.')
add(EL,'E15','TS process aliases/moduleResolution/typechecks/shared declarations','references/typescript-in-electron.md',[82,85,87,132,141],'verified','electron/main, electron/renderer, electron/common aliases official; aliases do not grant runtime capability; process config separation and explicit tsc separate from bundling appropriate. Exact TS NodeNext/bundler settings owner/version-dependent, not universal emitted defaults.')
add(EL,'E16','Decorators, emitDecoratorMetadata and electron-vite SWC option','references/typescript-in-electron.md',[132,322],'verified','Current electron-vite supports optional @swc/core and SWC decorators metadata path; absence built-in Vite/esbuild metadata support remains relevant. No evidence to remove SWC as obsolete.')
add(EL,'E17','App paths, safeStorage availability/weak Linux backend/session-only persistence','references/data-storage-native.md',[102,111,97],'correction-required','getPath userData/sessionData/logs/crashDumps/temp valid; safeStorage platform-dependent and basic_text weak fallback. Current async encrypt/decrypt APIs preferred; baseline policy correct but no version choice.','Keep session-only and backend validation; add async API branch/result shape only when feature needs it; do not promise universal vault.')
add(EL,'E18','File imports/dialogs/native modules/local data migrations','references/data-storage-native.md,references/native-os-integration.md',[88,89,102,117],'verified','Main-owned dialogs and cancellation/path validation, atomic app config and migration policies are task constraints; Electron ABI and ASAR checks are version-sensitive. No particular SQLite engine/transaction API is mandated, so library-specific SQL claims N/A.')
add(EL,'E19','Native menu/tray/global shortcut/dialog/clipboard/notification/desktop capture/display/power/theme','references/native-os-integration.md',[97,114,115,116,117,118,119,120,121,122,123,124,125],'correction-required','Named APIs owned by main are valid; Electron44 clipboard moved async/W3C and removed old renderer access; macOS42+ notifications require signing; capture/global shortcuts/Wayland require target-feature checks.','Add version-aware current native API branch; report target OS tested; do not fabricate old sync clipboard on44 or cross-OS proof.')
add(EL,'E20','React renderer routing/state/forms/offline UI and browser-only dependencies','references/renderer-integration.md',[82,83,85,87],'verified','Renderer framework remains browser-only with typed bridge; main owns privileged storage/lifecycle; server/query/UI state owner guidance matches process model. Framework/library selections remain project decisions, not mandatory Electron dependencies.')
add(EL,'E21','Playwright/WebdriverIO/Spectron and packaged runtime verification','references/testing-observability.md',[99,200,201],'verified','Playwright Electron support experimental; WebdriverIO service is maintained third-party with official owner docs; Spectron deprecated. Mocks cover policy only; real main/preload/renderer and packaged lane remain separate.')
add(EL,'E22','Main debugger/logging/crashReporter/netLog/contentTracing/performance','references/testing-observability.md',[98,100,126,127,128],'verified','Main inspector vs renderer DevTools, crash reporter initialization, netLog and contentTracing APIs supported. Production remote debugging unsafe; logs/dumps sensitive. Performance metrics are design budgets, not guaranteed numerical claims.')
add(EL,'E23','Review playbooks, output proof limits and direct owners','references/review-playbooks.md,fragments/overview.md,SKILL.md',[82,83,99,315],'verified','Architecture/security/native/source/build/TS/runtime review selectors agree with owning Electron facets. Evidence limits preserve OS and real-package distinctions except E10 same-artifact sequence.')

D='docusaurus-repo'
add(D,'D01','Scaffold/current stable engines and existing project compatibility','fragments/overview.md,SKILL.md,references/bootstrap-and-structure.md',[151,305,306,361],'correction-required','Docusaurus3.10.2 stable, Node>=20 accepted by core, React19 current scaffolds;3.9.2/React18 is separate existing-project branch. Latest scaffold MDX and faster defaults differ.','Add version-first/no unsolicited upgrade rule; distinguish framework minimum from combined toolchain and supported Node LTS.', 'Docusaurus3.10.2 stable;3.9.2 existing; React19/18; Node24 LTS')
add(D,'D02','pnpm create/install/run/exec workspace structure and frozen lockfile','references/bootstrap-and-structure.md,references/doc-quality-tooling-and-agents.md',[151,191,192,300],'verified','pnpm create docusaurus@latest site classic --typescript, workspace site directory and pnpm exec commands supported. Root package scripts/workspace filters should be discovered; frozen install belongs CI after a lockfile exists.')
add(D,'D03','Production serve CLI flags and repeated command examples','fragments/overview.md,SKILL.md,references/bootstrap-and-structure.md,references/search-and-ecosystem.md,references/deployment-versioning-i18n.md,references/doc-quality-tooling-and-agents.md,assets/project-files/AGENTS.md',[191,300,307,308],'correction-required','pnpm forwards flags after script without npm-style separator. Docusaurus serve has positional siteDir and --build option; literal -- shifts --build into siteDir.','Replace pnpm run serve -- --build with pnpm run serve --build or build then serve; remove unnecessary rebuild when validating frozen artifact; exact CLI probe required.')
add(D,'D04','Core config/presets/docs-only homepage/routes/sidebars/plugin IDs','references/config-presets-and-routing.md',[153,154,155,156,157,158,159,301],'verified','Classic preset includes docs/blog/pages; routeBasePath / with doc slug / requires removing page index collision; multi-instance id/path/routeBasePath/sidebarPath and navbar docsPluginId valid. Explicit config controls url/baseUrl/trailingSlash.')
add(D,'D05','MDX parser/Markdown frontmatter/links/assets/React browser-only constraints','references/content-authoring.md',[160,161,154,305],'correction-required','Docusaurus default markdown.format is mdx even for .md; detect makes extension matter.3.10 scaffolds now .mdx. MDX imports/React server rendering require browser-safe code.','Clarify .md extension does not disable MDX; preserve intentional authored format and current parser config, qualify new-scaffold default.')
add(D,'D06','Sidebars/categories/slug IDs/version-safe imports','references/content-authoring.md,references/config-presets-and-routing.md',[158,159,170,301],'verified','Autogenerated sidebars/category metadata/sidebar_position/slug supported; docs links resolve by IDs, routes differ. @site absolute imports remain stable when versioned docs move deeper.')
add(D,'D07','Mermaid/live-code/tabs/admonitions/code blocks and theme plugins','references/content-authoring.md',[162,163,164,165,303,304],'verified','markdown.mermaid + @docusaurus/theme-mermaid required; theme-live-codeblock in plugins is official supported example (not a defect). Live code SSR/browser restrictions and correct fenced syntax apply.')
add(D,'D08','ThemeConfig/colors/navbar/footer/prism/announcementBar/CSS/modules/swizzling','references/customization-and-ux.md',[166,167,168,300],'verified','Theme fields/examples and --list/--eject swizzle supported; @theme-original wrapper pattern valid. Unsafe swizzle API surface needs upgrade review; CSS variables and wrapped components minimize coupling.')
add(D,'D09','Algolia contextual search/crawler/facets/AskAI and credential boundary','references/search-and-ecosystem.md',[173,178,302],'verified','contextualSearch true default; version/language facets and crawler configuration needed; askAi assistant ID supported3.9+ DocSearch4. Search-only API key frontend, admin/crawler credentials external; current example field names supported.')
add(D,'D10','Local search @cmfcmf config/versions/locales/runtime/peer dependencies','references/search-and-ecosystem.md',[186,313,363],'verified','indexDocs/indexBlog/indexPages/language/maxSearchResults supported; versions/i18n supported; core^3, React18|19 peers. Search requires production build, not development mode.','Сохранить совместимую pinned version и production search probe; explicitly document dev limitation.')
add(D,'D11','Typesense config/node/React/Docusaurus support and crawler','references/search-and-ecosystem.md',[314,365],'verified','Owner README matrix0.27 supports Docusaurus>=3.9<4/Node20; own search service+crawler required. themes and typesenseCollectionName/typesenseServerConfig/contextualSearch structure owner-supported; do not imply server exists from UI config.')
add(D,'D12','OpenAPI generator/theme version matrix/generated trees and docs plugin integration','references/search-and-ecosystem.md',[188,364],'verified','Current5.x→Docusaurus3.10+, legacy4.x→3.5–3.9.2; plugin/theme pair and docItemComponent integration needed. Baseline correctly requires matrix check and source-owned generated docs.','В компактной reference записать current/legacy matrix as dated evidence, not forced upgrade; generated endpoint pages not hand-edited.')
add(D,'D13','Deployment url/baseUrl/trailingSlash/build/clear/static host and readback','references/deployment-versioning-i18n.md',[154,169,300,308],'verified','Static build + serving path prefix supported; clear removes generated state. Local serve handles baseUrl explicitly but is not canonical remote/CDN readback; host trailingSlash behavior separate.')
add(D,'D14','Versioning copies/current/latest/versioned roots/multi-instance commands','references/deployment-versioning-i18n.md',[157,170,301],'correction-required','Version command copies docs and sidebars; does not move current docs away. Current vs latest distinct, multi-instance roots use pluginId prefixes.','Replace move phrasing with snapshot copy; show named-instance and existing numbered-version conditions where needed.')
add(D,'D15','i18n content/UI JSON/React translations/version paths/locale URLs','references/deployment-versioning-i18n.md',[171,172,301],'correction-required','current path only current docs; archived version translation uses version-X and instance suffix. React pages use Translate/translate/code.json; copied pages translation path applies Markdown pages.','Differentiate Markdown and JSX, current/versioned/named-instance directories; test locale/version route and reload.')
add(D,'D16','Prettier/markdownlint config options/ignores/fix vs check-only','references/doc-quality-tooling-and-agents.md,assets/project-files/.prettierrc.json,assets/project-files/.prettierignore,assets/project-files/.markdownlint-cli2.jsonc,assets/project-files/AGENTS.md',[179,193,194,195,312],'verified','Prettier --check/--write/ignorePath and Markdownlint --fix/config.frontMatter/globs supported. gitignore string is valid schema. CI check-only and local fixes coherent; generated/node_modules excludes valid.')
add(D,'D17','Quality content coverage across non-default roots and versioned instances','references/doc-quality-tooling-and-agents.md,assets/project-files/.markdownlint-cli2.jsonc',[157,179,301,312],'correction-required','Fixed globs root/docs/blog/versioned/i18n miss skill-supported product/api/community and named-instance versioned roots. Green lint therefore omits requested authored content.','Derive globs from actual roots; verify representative bad Markdown from every authored tree is detected, generated exclusions explicit.')
add(D,'D18','GitHub Actions Node/tool engines/pnpm cache/install/scripts','references/doc-quality-tooling-and-agents.md,assets/project-files/.github/workflows/docs-quality.yml',[182,310,324,325,326,354,362],'correction-required','Mandatory latest markdownlint-cli2 0.23.2 engines Node>=22; workflow fallbackNode20 incompatible (and EOL). v4 Actions remain published version branches; latest action version alone is not defect.','Choose common supported runtime of core+lint+pnpm; keep project pin if compatible, identify conflict if not; new default Node24 or compatible22.')
add(D,'D19','New stable3.10 capabilities vs future.v4/experimental flags','references/config-presets-and-routing.md,references/bootstrap-and-structure.md',[154,305,309],'verified','3.10 Faster feature maturity and new scaffold defaults relevant to current owned build tasks; future.v4 are opt-in compatibility flags, not stablev4. No mandate to turn on every new feature.','Use when current build/config task requires; do not auto-migrate existing projects or assume all future flags stable.')
add(D,'D20','Direct documentation/frontend-design contract and verification authority','fragments/overview.md,SKILL.md',[155,156,167,169],'correction-required','Site ownership vs Diataxis/visual direction complementary. Existing text names owners but no handoff inputs/output or missing-owner continuation; universal pnpm start/build requirement can overrun read-only scope.','Add task mode/authority and usable direct handoff: validated content source+site route context, same snapshot/version; local useful work proceeds with dependent claim partial.')

VERSIONS={N:'Next16.3.4 stable; Next15 existing branch; React19.2; Node24 LTS',EL:'Electron44.3.0 stable; electron-vite5.0.0; Forge7.11.2; existing43/4 branch',D:'Docusaurus3.10.2 stable; existing3.9.2/React18 branch; Node24 LTS'}
for skill, rows in DATA.items():
    root=E/'baseline-packages'/skill
    inventory=[]
    for f in sorted(root.rglob('*')):
        if not f.is_file(): continue
        rel=str(f.relative_to(root)); text=f.read_text(); lines=text.splitlines()
        roles='supporting-history' if rel.startswith('docs/') else 'active-asset' if rel.startswith('assets/') else 'source' if rel in ['skill.yaml','fragments/overview.md'] else 'emitted' if rel=='SKILL.md' else 'active-reference' if rel.startswith('references/') else 'metadata-or-maintenance'
        ids=[r['id'] for r in rows if rel in r['source_files']]
        inventory.append(dict(file=rel, sha256=hashlib.sha256(f.read_bytes()).hexdigest(), line_count=len(lines), role=roles, aspect_ids=ids, technical_claim_identifiers=sorted(set(re.findall(r'`([^`\n]{1,150})`',text))) if roles!='supporting-history' else [], sections=[dict(line=i+1,title=l.lstrip('# ')) for i,l in enumerate(lines) if l.startswith('#')], assessment='covered by aspect IDs' if ids else 'N/A: historical supporting record, not current technical authority' if roles=='supporting-history' else 'N/A: metadata, generation, loading and maintenance rules; technical root repetition covered by linked overview/reference aspects'))
    for r in rows:
        r['verified_date']='2026-09-09'
        r['version']=r['version'] or VERSIONS[skill]
        r['evidence_boundary']='Official documentation/source comparison; no behavioral execution or product-runtime PASS from this row.'
        r['official_sources']=[{k:s[k] for k in ('url','final_url','file','retrieved_at','status','text_sha256') if k in s} for i in r.pop('official_source_ids') if (s:=BY_ID.get(i))]
        r['source_occurrences']=[dict(file=p,line_start=1,line_end=len((root/p).read_text().splitlines())) for p in r['source_files']]
        r['falsifier']='Claim contradicts the version-matched official API or fails the corresponding frozen API/runtime case; source comparison never substitutes for that execution.'
    result=dict(skill=skill,base_revision=BASE,baseline_manifest='baseline-snapshot.json',review_mode='independent-baseline-source-audit',verified_date='2026-09-09',release_channel='stable unless aspect explicitly says experimental or existing-project branch',coverage_method='All active baseline files read; equivalent claims grouped by aspect. File inventory preserves source/emitted/reference/asset identifiers and sections. Whole-file ranges describe occurrence search scope, not per-line execution. Historical records excluded from current technical authority.',technical_review_boundary='Source-grounded inventory. Downloaded is not synonymous with verified. Every aspect supplies a substantive comparison; unavailable/soft404 sources are excluded as positive evidence. Product APIs/commands and blind agent behavior still require coordinator trials.',aspects=rows,file_inventory=inventory,unverified_boundaries=['Baseline/candidate blind trials and catalog selection are not executed by this reviewer.','Real production Next/Supabase, Linux Electron packaging, Docusaurus browser/search and natural consumer handoffs remain with coordinator.','Windows/macOS signing/notarization/update install and external hosting/search/services are not verified.','OpenNext universal adapter support is not established; exact project adapter versions require owner source/probe.'] if skill==N else ['Baseline/candidate blind trials/catalog selection not executed by this reviewer.','Real runtime, consumer handoff and packaging/production UI probes remain with coordinator.','External publication and other OS capabilities are not verified.'])
    (E/f'technical-{skill if skill==N else "electron" if skill==EL else "docusaurus"}.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')
    print(skill,len(rows),'aspects',len(inventory),'files')
