from pathlib import Path
import json,re,hashlib,collections
E=Path(__file__).parent
B=E/'baseline-packages'
D='https://payloadcms.com/docs/'
G='https://github.com/payloadcms/payload/blob/v3.88.0/'
rows={s:[] for s in ['payload','payload-migration']}
def add(sk,id,aspect,locations,status,basis,change,sources,check):
 occ=[]
 for file,a,z in locations:
  p=B/sk/file; ls=p.read_text().splitlines(); z=min(z,len(ls))
  occ.append({'file':file,'start':a,'end':z,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
 rows[sk].append(dict(id=id,aspect=aspect,occurrences=occ,version='Payload 3.88.0 stable unless specified; installed project version must be established separately',checkedAt='2026-09-09',officialSources=[u if u.startswith('https:') else D+u for u in sources],result=status,basis=basis,requiredChange=change,falsifier=check,evidenceBoundary='Source/documentation review; code and agent execution not performed'))
def p(id,aspect,file,a,z,status,basis,change,sources,check):add('payload',id,aspect,[(file,a,z)],status,basis,change,sources,check)
def m(id,aspect,file,a,z,status,basis,change,sources,check):add('payload-migration',id,aspect,[(file,a,z)],status,basis,change,sources,check)
p('P-T01','Runtime, channels, installed-version discovery and dependency compatibility','skill.yaml',1,245,'correction-required','Root asks for project version but carries no stable/prerelease dependency basis. Stable npm tag and latest GitHub release are 3.88.0; canary is 4.0.0-canary.33. Installation docs require Node 20.9+, package engine also admits ^18.20.2; this is not an app compatibility guarantee. Exact @payloadcms/next peers exclude Next 15.5 and require patched 15.x or >=16.2.6<17.','Record stable versus existing project, same-version @payloadcms packages, installed peers and adapters; no unrequested upgrade.',['getting-started/installation',G+'packages/next/package.json',G+'packages/payload/package.json','https://registry.npmjs.org/-/package/payload/dist-tags','https://github.com/payloadcms/payload/releases/tag/v3.88.0'],'Version case preserves v2 while new v3 fixture rejects incompatible Next peer.')
p('P-T02','Source/generated root, Local API defaults, request threading and loop prevention','fragments/overview.md',1,158,'correction-required','Local API default overrideAccess=true is accurately warned; same req propagates request context/transaction and does not enable access checks by itself. Blanket atomicity requires adapter support and enabled transactions. Root transaction example lacks SQLite default qualification.','Preserve correct security rule; separate authorization and transaction propagation; state adapter prerequisite.',['local-api/access-control','database/transactions','database/sqlite'],'Actor request respects policy and injected nested write failure rolls back only when supported/enabled.')
p('P-T03','Collection CRUD access, Where return scope, admin entry and ordering','references/access-control.md',1,94,'correction-required','Collection create accepts boolean, read/update/delete/readVersions can use Where; admin gates Admin Panel access. beforeOperation precedes executeAccess in exact create operation. End note contradicts its own table by limiting Where to collection read.','Publish exact operation matrix and distinguish Admin visibility from access enforcement.',['access-control/collections',G+'packages/payload/src/collections/operations/create.ts'],'Create returns Where must not count as tenant enforcement; update/delete Where remain permitted.')
p('P-T04','RBAC/auth creation and roles privilege escalation','references/access-control.md',94,157,'correction-required','Roles field protects update only; collection has auth but no create policy, so authenticated default creation can write admin role on a new user. API admission and field create must enforce privilege assignment.','Protect create and update for privileged fields; explicit first-admin bootstrap boundary.',['access-control/fields','access-control/collections','authentication/overview'],'Ordinary authenticated actor cannot create another admin or promote itself.')
p('P-T05','Reusable access, ownership, query composition, headers and field access','references/access-control.md',158,409,'correction-required','Simple boolean/Where ownership and global/field distinction are supported. Field admin.hidden/condition is UI only. Optional id/user comparisons and header equality examples need actual identity/undefined handling; custom API key cannot infer missing env as authentication.','Keep valid patterns, explicit no-user guards; align field access argument availability and UI-only visibility.',['access-control/fields','access-control/globals','authentication/api-keys'],'Anonymous/undefined ids cannot satisfy owner rule; hidden field remains API-readable unless access denies it.')
p('P-T06','Tenant create and tenant field spoofing','references/access-control.md',410,471,'correction-required','tenantAccess returns a Where and is assigned create. Exact executeAccess rejects only falsy and create does not constrain data by that Where. Field hook fills tenant only if !value, preserving attacker-supplied other tenant.','Boolean create authorization and server-owned tenant assignment or explicit input equality validation; field create/update control.',['access-control/collections',G+'packages/payload/src/auth/executeAccess.ts',G+'packages/payload/src/collections/operations/create.ts'],'Tenant A cannot create document for B even when supplying B id.')
p('P-T07','Auth self/admin, cross-collection count and arguments','references/access-control.md',472,697,'correction-required','count returns object {totalDocs}, but delete rule compares entire count result ===0. Hooks/access argument availability differs by operation; notes incorrectly say only collection read supports Where and all access runs before hooks.','Destructure totalDocs, preserve req, handle missing id/user; unify exact matrix.',['local-api/overview','access-control/collections','access-control/fields',G+'packages/payload/src/collections/operations/count.ts'],'Unreferenced record can delete; referenced record cannot; no undefined-id access lookup.')
p('P-T08','Context, tenant, user-agent, IP and time-based access examples','references/access-control-advanced.md',1,177,'correction-required','Context and Date logic are ordinary app policy; forwarded headers and user-agent do not authenticate an actor. Listed CIDR strings are tested with exact string includes, not network containment. Exact IP allowlist cannot evaluate CIDR.','Use a declared trusted proxy identity boundary and real parsed IP ranges only when required; distinguish contextual hints from authorization.',['access-control/overview',G+'packages/payload/src/fields/config/types.ts'],'Spoofed forwarded IP/user-agent cannot confer access; CIDR member and nonmember are evaluated accurately.')
p('P-T09','Subscription access, factory functions, configurations and diagnostics','references/access-control-advanced.md',178,570,'correction-required','Several callbacks destructure req:{user} then reference req, so they throw ReferenceError. Application policies are illustrative rather than built-in Payload subscriptions.','Keep req object and derive user; type against Access; label app-supplied data/helpers.',['access-control/collections',G+'packages/payload/src/collections/config/types.ts'],'Typecheck and invoke each retained callback with authenticated and missing user.')
p('P-T10','Access caching and per-query versus per-document performance','references/access-control-advanced.md',571,704,'correction-required','Collection find evaluates collection read policy once for query, not once per returned document. FieldAccess lacks top-level context; use req.context. False cached results require presence check, not truthiness.','Remove incorrect N+1 claim, use actual request-scoped cache and arguments.',['access-control/fields',G+'packages/payload/src/collections/operations/find.ts',G+'packages/payload/src/fields/config/types.ts'],'Multiple document result evaluates collection policy at query boundary; cached denial stays denial.')
p('P-T11','Mongo/Postgres/SQLite adapters, IDs and DB requirements','references/adapters.md',1,49,'verified','Named mongooseAdapter/postgresAdapter/sqliteAdapter and connection configuration are present in current docs. Mongo transactions need replica set; SQL default ID shape differs from Mongo and uuid/uuidv7 branches.','Add installed adapter/engine evidence before inferring compatibility; v3.83 uuidv7 is optional, not mandatory update.',['database/mongodb','database/postgres','database/sqlite','https://github.com/payloadcms/payload/releases/tag/v3.83.0'],'Load exact declared adapter configuration and verify chosen ID shape.')
p('P-T12','Automatic/manual transactions and migration CLI operations','references/adapters.md',50,154,'correction-required','Same req and await are required for nested operations; overrideAccess=true does not remove transaction need. SQLite disables transactions by default; set transactionOptions:{} to enable. beginTransaction may return null without support. Migration up/down/status exist; reset/refresh/fresh are destructive paths.','Qualify atomicity, check transaction support, distinguish schema migrations and data imports; use installed declared CLI and explicit destructive boundary.',['database/transactions','database/migrations','database/sqlite',G+'packages/payload/src/database/migrations/migrate.ts'],'Force nested write failure and inspect persisted state; migration create/up/status on disposable DB only.')
p('P-T13','Storage: S3, R2, Azure, GCS, Vercel Blob and Payload Cloud','references/adapters.md',155,290,'correction-required','Current standalone storage packages are correct family. R2 example supplies string bucket and S3 config; stable r2Storage requires Cloudflare R2Bucket binding. S3 credentials/endpoints belong to s3Storage branch. Remote availability is untested.','Replace R2 example with binding or explicit S3-compatible alternative; keep provider credentials/runtime requirements separate.',['upload/storage-adapters',G+'packages/storage-r2/src/index.ts','https://github.com/payloadcms/payload/releases/tag/v3.74.0'],'Exact R2 config typecheck; real provider readback required for remote claim.')
p('P-T14','Email adapter configuration and delivery boundary','references/adapters.md',291,326,'verified','Official email documentation directly matches retained nodemailerAdapter transportOptions host/port/auth and resendAdapter apiKey/from fields. Full options examples were read. No delivery was attempted.','Preserve version-matched packages and provider boundary; do not infer delivery from sendEmail resolve.',[G+'docs/migration-guide/overview.mdx','email/overview'],'Configured adapter loads; controlled provider delivery only within authorized environment.')
p('P-T15','Auth login, reset, custom strategies and API keys','references/advanced.md',1,80,'correction-required','Login/forgotPassword and API-key-only options match current APIs. Strategy is not exported by payload 3.88.0; exact source exports AuthStrategyFunction/Args/Result. Auth callback must return a Payload user document or null; verifyToken is an unspecified application helper. Custom strategy changes require server restart.','Use exported AuthStrategyFunction or type auth.strategies through CollectionConfig; specify verifyToken trust contract and distinguish local token from browser cookie/session.',['authentication/operations','authentication/custom-strategies','authentication/api-keys'],'Login/session readback and invalid credentials; no token/cookie leaked in evidence.')
p('P-T16','Jobs tasks, workflows, inline API, worker execution and retries','references/advanced.md',81,156,'correction-required','job.runInlineTask does not exist in stable WorkflowHandler. Handler receives inlineTask and tasks; inlineTask(taskId,{task,input}) is supported. queue creates a pending job; a worker/run operation must process it. v3.71 added optional concurrency; v3.85 fixed no-retries loop.','Use exact stable handler API and document queue→run→terminal result; preserve idempotent step ids and failure distinction.',['jobs-queue/workflows','jobs-queue/queues',G+'packages/payload/src/queues/config/types/workflowTypes.ts','https://github.com/payloadcms/payload/releases/tag/v3.85.0'],'Task is queued, run, completes and output is visible; queued-only cannot pass.')
p('P-T17','Custom endpoints and default Local API privilege','references/advanced.md',157,218,'correction-required','Featured collection endpoint invokes req.payload.find without overrideAccess:false; active detailed reference repeats that defect. PayloadRequest presence does not enforce caller permissions.','All caller-scoped operations carry req and overrideAccess:false; explicit system operation requires actual task reason.',['local-api/access-control','rest-api/overview'],'Anonymous and tenant actors receive only allowed records.')
p('P-T18','Custom React components and views','references/advanced.md',219,273,'correction-required','Client component invokes useField without {path}; custom view imports server DefaultTemplate into client and omits required init props. File paths/import map and client/server split are required in v3.','Use typed field props/path and server view template; verify rendered Admin.',['custom-components/overview','admin/react-hooks',G+'packages/next/src/templates/Default/index.tsx'],'Generated import map resolves; custom field edits correct nested path; view renders.')
p('P-T19','Official plugins, localization and exported type reference list','references/advanced.md',274,386,'correction-required','plugin-search stores first-party indexed records; no built-in Algolia support claimed by official docs. Redirects plugin manages data and requires frontend redirect implementation. Import-export supports CSV and JSON with job runner requirements. Localization sample uses unimported TextField and buildConfig fragments lack db. main source links follow development branch rather than installed stable.','Fix plugin capability summaries, missing snippet imports/prerequisites; use tag/installed exports instead of main; distinguish configured redirects from observed HTTP redirect.',['plugins/overview','configuration/localization','typescript/overview'],'Each import/config resolves under locked versions; no fallback masquerades as translated field.')
p('P-T20','Basic/auth/upload collections and Globals','references/collections.md',1,125,'correction-required','Basic field/collection/upload config is supported, but auth roles are not guarded on create/update. Image resizing requires supplied sharp dependency in v3; collection examples alone are not complete buildConfig.','Guard privileged roles; mark schema fragments and complete required runtime dependencies where called runnable.',['configuration/collections','upload/overview',G+'docs/migration-guide/overview.mdx'],'Actor cannot set admin role; upload creates a retrievable file.')
p('P-T21','Live preview, draft visibility and version status','references/collections.md',126,303,'correction-required','_status stored values are draft/published; changed is UI state, not persisted enum. Draft enablement is not authorization: public read requires published filter. URL config alone is not frontend live-preview listener/rendering. Globals config/access supported.','Fix draft claims and distinguish preview URL from live-update end-to-end wiring.',['versions/drafts','live-preview/overview',G+'packages/payload/src/versions/baseFields.ts','configuration/globals'],'Anonymous cannot read drafts; editor change appears in preview if live claim is made.')
p('P-T22','Endpoint request/response, paths, body parsing and helper signatures','references/endpoints.md',1,307,'correction-required','v3 uses Web Request/Response and routeParams, no Express res/next. JSON/file body and locale helpers need awaiting and correct package exports. Actual request-specific CRUD examples omit overrideAccess:false.','Preserve current response/body patterns but bind all actor operations to access; avoid body double-consumption; verify helper export paths.',['rest-api/overview',G+'packages/payload/src/utilities/addDataAndFileToRequest.ts',G+'packages/payload/src/utilities/addLocalesToRequest.ts',G+'docs/migration-guide/overview.mdx'],'JSON/multipart and route params work; unauthorized request cannot perform CRUD.')
p('P-T23','Endpoint examples: custom search, upload, preview, placement and factories','references/endpoints.md',308,634,'correction-required','Real-world examples and best-practice claim that req.payload ensures access conflict with Local API default bypass. Authentication check alone is insufficient. OpenAPI comments are metadata, not installed API specification generation.','Correct every example and misleading best-practice line; mark application helpers/framework integration prerequisites.',['rest-api/overview','local-api/access-control'],'Same actor input yields same allowed set as standard REST API; upload/publish deny cases covered.')
p('P-T24','Structural/capability/data/layout/tab/option guards and traversal','references/field-type-guards.md',1,553,'correction-required','Exact stable guard source differs from copied signatures: fieldSupportsMany includes upload runtime; fieldHasMaxDepth includes join; fieldAffectsData also admits virtual fields; optionsAreObjects checks first option only; fieldIsHiddenOrDisabled checks field.hidden/admin.disabled. Recursive traversal shown skips blocks and tabs.','Use installed exported guards and describe actual predicate; traverse all nested containers explicitly; do not claim persistence solely from name guard.',[G+'packages/payload/src/fields/config/types.ts'],'Mixed/nested schema visits fields inside blocks and named/unnamed tabs; guard examples match exact exports.')
p('P-T25','Text validation, experimental slug helper and Lexical features','references/fields.md',1,156,'correction-required','Custom text validate replaces default constraints; Boolean(value) does not preserve minLength/maxLength. slugField is experimental in stable source. EXPERIMENTAL_TableFeature needs explicit experimental boundary. Feature replacement must preserve intended defaults.','Wrap built-in validator or avoid redundant override; label experimental/version requirements and typecheck imports.',['fields/text','rich-text/official-features',G+'packages/payload/src/fields/baseFields/slug/index.ts'],'Short nonempty value fails declared minimum; optional experimental helper exists in exact version.')
p('P-T26','Relationships, arrays, blocks, select and upload shapes','references/fields.md',157,302,'verified','Single/hasMany/polymorphic relationship structures and corresponding config fields are supported. Storage uses returned Payload document IDs; population depth may return IDs or objects.','Preserve configured relationTo/cardinality; optional newer polymorphic uploads do not force changes.',['fields/relationship','fields/array','fields/blocks','fields/select','fields/upload'],'Create/read representative single, multiple and polymorphic relationship with depth0 and depth1.')
p('P-T27','Point operators, joins, virtual fields and UI-only conditions','references/fields.md',303,465,'correction-required','Point data is [longitude,latitude]. near expects combined comma tuple; separate maxDistance/minDistance operator keys shown are invalid. SQLite geospatial query capability is limited. Join on collection relationship is supported; virtual fields not persisted, UI conditions not security.','Fix near syntax and adapter boundaries; preserve ownership/relationship source and virtual anti-claim.',['fields/point','queries/overview','fields/join','fields/overview'],'Known inside/outside distance points filter correctly on supported adapter; virtual value absent from DB storage.')
p('P-T28','Radio/row/collapsible/UI/tabs/groups and field factories','references/fields.md',466,744,'correction-required','Field layouts and component paths are supported; custom deepMerge performs shallow spreads and can discard nested admin defaults. appearances argument is accepted but not used to restrict radio options.','Use accurately named shallow merge or real tested recursive merge; make accepted factory options affect output.',['fields/radio','fields/row','fields/collapsible','fields/ui','fields/tabs','fields/group'],'Factory override retains unrelated nested defaults and emitted appearance options equal input contract.')
p('P-T29','Hooks lifecycle, context and date auto-set','references/hooks.md',1,186,'correction-required','Hook APIs/context are current. afterRead computes only output; beforeChange input is unvalidated and partial on update. Revalidation sample needs Next-specific cache API version grounding and failure propagation.','Bind hook phase, partial data/originalDoc, same req and loop guard; hand Next cache behavior to installed nextjs owner.',['hooks/overview','hooks/collections','hooks/fields','hooks/context',G+'packages/payload/src/collections/operations/create.ts'],'No loop; partial update preserves missing fields; failure does not produce false cache/data success.')
p('P-T30','Plugin packaging, exports, build commands and peers','references/plugin-development.md',1,177,'correction-required','Plugin functions Config→Config/Promise supported. Example next^15.4.10 is incompatible with current patched peer minimum and admits excluded minors. SWC command correctly declares @swc/core but its referenced .swcrc is not supplied in the fragment. Example lacks graphql peer and does not establish exact package compatibility.','Use exact official template as version-scoped basis; verify declared build plus packed installed consumer import rather than isolated source compile.',['plugins/build-your-own',G+'templates/plugin/package.json',G+'packages/next/package.json'],'Fresh plugin build/package install/import works against locked Payload fixture.')
p('P-T31','Plugin fields/hooks/endpoints/overrides/tabs/disabled behavior/i18n/onInit','references/plugin-development.md',178,613,'correction-required','Composition should preserve existing config. onInit seed supplies string id seeded-by-plugin without custom ID schema; default SQL numeric IDs cannot accept it. Disabled-schema preservation is a deliberate plugin policy, not generic system default. Some overrides drop nested settings.','Use natural unique seed key and returned ID or explicit ID schema; preserve config/hook order; describe disabled plugin behavior.',['plugins/plugin-api','plugins/build-your-own','database/postgres','configuration/collections'],'Existing config/hook survives plugin; repeated init does not duplicate records; SQL seed succeeds.')
p('P-T32','Plugin TypeScript, client field, composition and async configuration','references/plugin-development.md',614,1044,'correction-required','Basic typed custom field useField({path}) is valid. Async plugin example may dereference optional config or append undefined; hooks map mutates collection.hooks without initializing it. Type/schema augmentation must match actual exports.','Typecheck complete retained fragments and invoke optional empty configuration; preserve existing config.',['plugins/plugin-api','custom-components/overview',G+'packages/payload/src/config/types.ts'],'Plugin called with default/empty options and collections with no hooks returns valid config.')
p('P-T33','Plugin authorization/filter composition','references/plugin-development.md',1045,1116,'correction-required','Wrapper puts original boolean/Promise directly in Where.and, so deny and async policy do not have defined correct composition. baseListFilter is deprecated and function typed, not static Where; filterOptions may static or async callback with full args, while example calls with relationTo string and undefined req.','Await original policy; false stays false, true becomes tenant filter, Where combines with tenant; use current baseFilter function and preserve filterOptions forms.',['access-control/collections',G+'packages/payload/src/collections/config/types.ts',G+'packages/payload/src/fields/config/types.ts',G+'packages/plugin-multi-tenant/src/index.ts'],'Original false denies; true/Where/Promise resolve correctly; no boolean/Promise is serialized into where.')
p('P-T34','Plugin admin metadata/providers/actions/views and recursive background work','references/plugin-development.md',1117,1295,'correction-required','Arbitrary plugin metadata belongs to custom/admin.custom, not typed admin.meta; providers belong root admin.components, not collection. beforeFields is not current collection slot. Recursive resave requires pagination and req; omitted pagination reads first10 only.','Use actual typed slots, remove false From plugin attribution unless exact; iterate entire child set with cycle safeguards and transaction req.',['custom-components/custom-providers',G+'packages/payload/src/collections/config/types.ts',G+'packages/payload/src/config/types.ts','queries/pagination'],'Admin resolves components, metadata is available where intended, >10 children all processed without cycles.')
p('P-T35','Plugin dev fixture, Vitest/Playwright tests and package verification','references/plugin-development.md',1296,1436,'verified','Test APIs describe optional integration/browser fixtures. Exact createPayloadRequest accepts Request and Promise<SanitizedConfig>, getPayload/destroy are present; Vitest test/expect and Playwright page/expect syntax is valid. vitest defaults to watch, one-shot requires run. Fixtures are fragments and source handler calls do not prove HTTP routing or packed consumer interoperability. Package-version compatibility remains P-T30; no command was executed.','Verify declared scripts/dependencies in safe fixture, keep current runner and installed-package boundary; no permanent harness required.',['plugins/build-your-own',G+'templates/plugin/package.json','https://vitest.dev/guide/','https://playwright.dev/docs/intro'],'Declared commands run fresh fixture and packed import resolves; test process shuts down.')
p('P-T36','Query operators, nested filters, Local/REST/GraphQL and pagination','references/queries.md',1,274,'correction-required','Where/and/or/dotted fields and CRUD/REST/GraphQL shapes are documented. all operator is Mongo-only; depth has no GraphQL effect; defaultDepth2 and pagination10 apply outside GraphQL shape. req is needed for transaction even if overrideAccess=true, contrary to optional wording.','Add operator/adapter limits, retain correct bypass warning and distinguish req transaction role.',['queries/overview','queries/depth','queries/pagination','local-api/overview','graphql/overview'],'Adapter-appropriate filters return expected set; totalDocs read as property; nested administrative write shares transaction.')
m('M-T01','Outcome, authorization, activation, complete model and import ownership','skill.yaml',1,165,'correction-required','Description promises migration but workflow ends at planning/offer script; hard-coded confirm complete model can re-ask already supplied authorization. Direct interop narrows migration to mapping and leaves actual durable execution/reconciliation owner unstated.','Migration owns authorized transformation/import/rerun/reconciliation; reuse accepted model and authority, stop only missing dependent fact/action.',['local-api/outside-nextjs','local-api/overview'],'M01 runs authorized import with accepted schema; M04 plans only when import is not authorized.')
m('M-T02','Generated workflow overview, dynamic enum choices and promised outputs','fragments/overview.md',1,142,'correction-required','Config-first sequencing useful for unknown schema, but repeated every-collection confirmation is unconditional. Direct assignment field schema snippets omit explicit import despite copy-ready instruction. User-approved fixed enum should not be reopened.','Unify source/generated path, minimum input and accepted decision reuse; distinguish config, plan, execution and verified result.',['configuration/collections','fields/select','fields/relationship'],'Accepted enum is preserved; sufficient authorized input reaches import without unrelated confirmation.')
m('M-T03','Field schema universal base and type fidelity','references/payload-field-reference.md',1,61,'correction-required','Pseudo BaseField claims all fields require name, conflicting with layout fields; hidden comment says admin-only though field.hidden also removes default API output. label and callback types are narrowed too far for current public Field union.','Use Payload exported types and clearly illustrative subset, not complete schema; distinguish admin.hidden from field.hidden.',['fields/overview',G+'packages/payload/src/fields/config/types.ts'],'Generated complete config typechecks with unnamed layout fields and intended visibility.')
m('M-T04','Scalar text/textarea/number/email/date/checkbox fields and transforms','references/payload-field-reference.md',62,357,'correction-required','Text/textarea/number/checkbox properties mostly match. Email does not support copied minLength/maxLength options. Unix timestamp conversion new Date(timestamp) treats number as milliseconds; seconds require scaling. Dates need source timezone and null policy.','Remove unsupported Email props; explicit seconds/ms/ISO/date-only branches; validate absent/null/value before coercion.',['fields/text','fields/textarea','fields/number','fields/email','fields/date','fields/checkbox','https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date'],'Seconds1700000000 and milliseconds1700000000000 produce same intended instant; nullable value preserved.')
m('M-T05','Rich text editor config, HTML/Markdown/Slate/AST conversion','references/payload-field-reference.md',147,193,'correction-required','Payload richText requires configured editor, not raw HTML; Lexical is default template choice, not magic acceptance of HTML. Converters require actual editor configuration. HTML img and Markdown URLs are not auto-uploaded to Payload.','Choose installed editor, transform source shape, preimport/remap media and internal links; unknown nodes reported as incomplete rather than silently dropped.',['fields/rich-text','rich-text/converting-html','rich-text/converting-markdown','rich-text/migration'],'Formatting, internal relation and embedded media render after restart; unknown node or failed media prevents complete claim.')
m('M-T06','Select/radio, relationship and upload schemas/cardinality/filterOptions','references/payload-field-reference.md',352,613,'correction-required','Core enum/relation/upload patterns supported. Relationship and upload can be polymorphic in current stable; filterOptions accepts Where or full callback/Promise. Source IDs and URLs are not Payload relation IDs.','Use exact exported field types; accepted schema governs cardinality; durable source-to-target mapping and unresolved link handling.',['fields/select','fields/radio','fields/relationship','fields/upload',G+'packages/payload/src/fields/config/types.ts'],'Single/hasMany/polymorphic identities resolve to existing correct target records.')
m('M-T07','Array/group/blocks nested mappings and deprecated block images','references/payload-field-reference.md',614,871,'correction-required','Core nested models supported; blocks imageURL/imageAltText are deprecated since v3.79 in favor of images icon/thumbnail. Mapping must preserve array order/blockType and subtype fields.','Replace deprecated main path with images API; explicit version branch for old installed projects; preserve subtype and order.',['fields/array','fields/group','fields/blocks','https://github.com/payloadcms/payload/releases/tag/v3.79.0'],'Nested ordered content round-trips with actual configured block slugs and image options.')
m('M-T08','JSON schema and fallback data','references/payload-field-reference.md',872,925,'correction-required','jsonSchema expects wrapper containing uri/fileMatch/schema; example gives raw JSON Schema. json fallback preserves bytes but does not prove meaning or renderer capability.','Correct wrapper per exact type and label unknown raw preservation versus successful semantic conversion.',['fields/json',G+'packages/payload/src/fields/config/types.ts'],'Config typechecks; expected invalid JSON detected by actual validator, unknown source stays unresolved.')
m('M-T09','Point, row/collapsible/tabs/UI and layout fields','references/payload-field-reference.md',926,1099,'correction-required','Point API stores coordinate pair rather than universal GeoJSON shape; geospatial operations depend on adapter. Layout fields differ in name requirements, UI is not stored, named/unnamed tabs change persisted nesting.','Use current exported field union, correct pair mapping and adapter limitation; no storage claims from UI layout.',['fields/point','fields/code','fields/row','fields/collapsible','fields/tabs','fields/ui'],'Lat/lon not swapped; layout grouping is reflected correctly in persisted shape; UI-only data not asserted.')
m('M-T10','Auth/upload/localization/version collection configuration','references/payload-field-reference.md',1100,1181,'correction-required','Auth role select lacks field protections. upload.staticURL was removed in v3; s3Adapter comment is legacy standalone adapter migration. Localization root config plus fields is needed; fallback defaults true. Draft status source policy is separate from standard enum.','Fix current upload storage family and role boundaries; preserve v2 only explicit installed branch; validate locales without fallback and source publication policy.',['upload/overview','configuration/localization','versions/drafts',G+'docs/migration-guide/overview.mdx'],'New v3 config loads and file URL works; v2 remains unchanged; en/it read with fallbackLocale:false matches source.')
m('M-T11','WordPress REST v2/export/DB and ACF mapping','references/payload-field-reference.md',1182,1198,'correction-required','Table mixes DB post_title/post_content/post_author with REST featured_media. REST title/content are rendered/raw objects; status set includes publish/private/future/etc, not Payload draft/published identity. Date fields have site timezone versus GMT. ACF repeater/group/flexible mapping is conceptual and subtype-dependent.','Name source format/version; explicit status/timezone/HTML conversion and ACF subtype mapping rather than direct column rename.',['https://developer.wordpress.org/rest-api/reference/posts/','https://developer.wordpress.org/rest-api/reference/media/','https://www.advancedcustomfields.com/resources/repeater/','https://www.advancedcustomfields.com/resources/group/','https://www.advancedcustomfields.com/resources/flexible-content/'],'REST and DB samples map independently; private/future source is not silently published; images survive HTML conversion.')
m('M-T12','Contentful schema, assets, links and locale objects','references/payload-field-reference.md',1199,1213,'correction-required','Scalar family mapping is conceptual; Rich Text JSON AST includes linked entries/assets and localization response differs by API/export. sys identity and environment/space context must survive mapping.','Expand only execution-relevant source contract: explicit raw export/API, identity namespace, entry/asset link resolution, actual locale values and conversion.',['https://www.contentful.com/developers/docs/concepts/rich-text/','https://www.contentful.com/developers/docs/concepts/links/','https://www.contentful.com/developers/docs/concepts/data-model/'],'Raw exported locale/link object never becomes literal field string or wrong Payload ID; embedded links render.')
m('M-T13','Strapi5 versus older source formats and CMS-only trigger branches','references/payload-field-reference.md',1214,1252,'correction-required','Strapi5 richtext Markdown and blocks AST are distinct; documentId differs from numeric id and REST5 shape differs v4. Dynamiczones/components require subtype/field mapping. Sanity is mentioned in trigger but has no conversion path; Portable Text/_ref are not Lexical. Webflow only trigger; API assertions absent so N/A for existing technical example, not certified support.','Identify actual source release/API/export; exact format-specific converters; inspect Sanity schema/PortableText when selected; do not invent Webflow semantics.',['https://docs.strapi.io/cms/backend-customization/models','https://docs.strapi.io/cms/api/rest','https://www.sanity.io/docs/apis-and-sdks/introduction-to-schemas','https://www.sanity.io/docs/developer-guides/beginners-guide-to-portable-text'],'Same sample from each source shape yields expected target value; unknown shape reports exact needed input.')
m('M-T14','Import scripts, crash/rerun, cycles, media failures and full reconciliation','SKILL.md',225,263,'correction-required','Current plan names source-ID mapping and representative verification but does not define durable identity, restart semantics, two-pass/cyclic relations, checkpoint/errors, source-vs-target set reconciliation or missing locale/media classification. User requested reliable execution, not only schema/plan.','Add owning workflow through authorized import, deterministic rerun/checkpoint, failure classification and complete source-ID/count/locale/relationship/media reconciliation; exact public readback when requested.',['local-api/outside-nextjs','local-api/overview','queries/pagination','configuration/localization','rich-text/converting-html'],'Crash+temporary media failure then restart creates no duplicate records/media; all source ids/locales accounted for; exit0 alone insufficient.')
# Inventory entire physical surface and every active markdown section/code fence; rows can overlap deliberately.
for sk,aspects in rows.items():
 files=[]; sections=[]; blocks=[]; tokenocc=[]
 for f in sorted((B/sk).rglob('*')):
  if not f.is_file():continue
  rel=str(f.relative_to(B/sk)); ls=f.read_text().splitlines(); ids=[r['id'] for r in aspects if any(o['file']==rel for o in r['occurrences'])]
  if rel=='SKILL.md' and sk=='payload':ids=['P-T01','P-T02']
  if rel=='SKILL.md' and sk=='payload-migration':ids+=['M-T01','M-T02']
  files.append({'file':rel,'lines':len(ls),'sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'surface':'supporting-history' if rel.startswith('docs/') else 'active-or-maintenance','aspectIds':ids,'classification':'N/A technical API assertion' if rel.startswith(('docs/','agents/')) or rel=='AGENTS.md' else 'covered by aspect rows; generated counterparts derive from identical source snippets'})
  if f.suffix=='.md' and not rel.startswith('docs/'):
   starts=[(i+1,l) for i,l in enumerate(ls) if re.match(r'^#{1,4} ',l)]
   for k,(a,h) in enumerate(starts):
    z=(starts[k+1][0]-1 if k+1<len(starts) else len(ls)); rs=[r['id'] for r in aspects if any(o['file']==rel and o['start']<=z and o['end']>=a for o in r['occurrences'])]
    sections.append({'file':rel,'start':a,'end':z,'heading':h,'aspectIds':rs or ids,'scope':'instruction/metadata' if not(rs or ids) else 'technical-or-workflow'})
   start=None
   for i,l in enumerate(ls,1):
    if l.startswith('```'):
     if start is None:start=(i,l[3:])
     else:
      rs=[r['id'] for r in aspects if any(o['file']==rel and o['start']<=i and o['end']>=start[0] for o in r['occurrences'])]
      blocks.append({'file':rel,'start':start[0],'end':i,'language':start[1],'aspectIds':rs or ids,'execution':'not run'});start=None
    for match in re.findall(r'`([^`\n]+)`',l):
     if re.search(r'pnpm |npm |npx |--|\(|[.]|@payload|Payload|^(read|write|create|update|delete|find|count|db|auth|upload|fields|hooks|plugins|select|relationship|hasMany|near|within|intersects|depth|locale|fallback)',match):tokenocc.append({'file':rel,'line':i,'assertionToken':match})
 data={'skill':sk,'mode':'independent baseline technical source audit','base':'d89d66f2c99bf8b9e84e5b4def54fa60192856a5','sourceVersion':'0.1.0' if sk=='payload' else '0.1.1','checkedAt':'2026-09-09','stable':'3.88.0','prerelease':'4.0.0-canary.33; not a recommended upgrade','existingProject':'none supplied; no installed product version inferred','snapshot':'baseline-snapshot.json','sourceArchive':'payload-official/ (official docs, exact v3.88 source, release feed, npm tags)','coverageClaim':'All target active files and sections inventoried. Result applies to explicitly stated source claims, not every example runtime. Unverified rows remain open and prohibit a full currentness/PASS claim.','technicalAspects':aspects,'fileInventory':files,'sectionInventory':sections,'codeBlockInventory':blocks,'inlineTechnicalTokens':tokenocc,'counts':dict(collections.Counter(x['result'] for x in aspects)),'unperformed':['blind agent executions','installed API probes','database/browser/provider execution','compiler checks and pnpm test:ci delegated to root'],'N_A':[{'aspect':'Product deployment/provider credentials','reason':'No product or provider environment is supplied/authorized to this reviewer; source review is applicable, remote execution not performed.'},{'aspect':'Supporting historic logs as current instruction source','reason':'Classified as supporting, not loaded as active normative API instructions; hashes preserved.'}]}
 (E/f'technical-{sk}.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
 print(sk,len(aspects),'aspects',len(sections),'sections',len(blocks),'codeblocks',data['counts'])
