import { EXIT_USAGE } from './exit-codes.ts';

export const ERROR_CODES = [
  'BE_USAGE_INVALID',
  'BE_ROOT_NOT_FOUND',
  'BE_ROOT_ALREADY_EXISTS',
  'BE_ROOT_NOT_EMPTY',
  'BE_INVALID_JSON',
  'BE_SCHEMA_INVALID',
  'BE_INPUT_FILE_NOT_FOUND',
  'BE_SOURCE_NOT_FOUND',
  'BE_SOURCE_FILE_MISSING',
  'BE_SOURCE_READ_FAILED',
  'BE_SOURCE_KIND_INVALID',
  'BE_SOURCE_AUTHORITY_INVALID',
  'BE_PACKET_ITEM_ALREADY_EXISTS',
  'BE_PACKET_DUPLICATE_ITEM_KEYS',
  'BE_CONTEXT_CONFLICT_GLOSSARY',
  'BE_CONTEXT_CONFLICT_ENTITY',
  'BE_DEPENDENCY_NOT_FOUND',
  'BE_PATCH_TARGET_NOT_FOUND',
  'BE_PATCH_ID_CONFLICT',
  'BE_PATCH_SEQUENCE_CONFLICT',
  'BE_PATCH_OPERATION_INVALID',
  'BE_TODO_REFRESH_MANAGED',
  'BE_TODO_NOT_FOUND',
  'BE_ITEM_NOT_FOUND',
  'BE_CANONICAL_WRITE_FAILED',
  'BE_REPORT_WRITE_FAILED',
  'BE_TEMPLATE_OUTPUT_INVALID',
  'BE_DELETE_CONFIRM_REQUIRED',
  'BE_MUTATION_LOCKED',
  'BE_PLATFORM_UNSUPPORTED',
  'BE_INTERNAL_STATE_CORRUPT',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export const ERROR_EXIT_CODES = {
  BE_USAGE_INVALID: EXIT_USAGE,
  BE_ROOT_NOT_FOUND: 5,
  BE_ROOT_ALREADY_EXISTS: 4,
  BE_ROOT_NOT_EMPTY: 4,
  BE_INVALID_JSON: 3,
  BE_SCHEMA_INVALID: 3,
  BE_INPUT_FILE_NOT_FOUND: 5,
  BE_SOURCE_NOT_FOUND: 5,
  BE_SOURCE_FILE_MISSING: 5,
  BE_SOURCE_READ_FAILED: 5,
  BE_SOURCE_KIND_INVALID: EXIT_USAGE,
  BE_SOURCE_AUTHORITY_INVALID: EXIT_USAGE,
  BE_PACKET_ITEM_ALREADY_EXISTS: 4,
  BE_PACKET_DUPLICATE_ITEM_KEYS: 4,
  BE_CONTEXT_CONFLICT_GLOSSARY: 4,
  BE_CONTEXT_CONFLICT_ENTITY: 4,
  BE_DEPENDENCY_NOT_FOUND: 4,
  BE_PATCH_TARGET_NOT_FOUND: 5,
  BE_PATCH_ID_CONFLICT: 4,
  BE_PATCH_SEQUENCE_CONFLICT: 4,
  BE_PATCH_OPERATION_INVALID: 4,
  BE_TODO_REFRESH_MANAGED: 4,
  BE_TODO_NOT_FOUND: 5,
  BE_ITEM_NOT_FOUND: 5,
  BE_CANONICAL_WRITE_FAILED: 1,
  BE_REPORT_WRITE_FAILED: 1,
  BE_TEMPLATE_OUTPUT_INVALID: EXIT_USAGE,
  BE_DELETE_CONFIRM_REQUIRED: 6,
  BE_MUTATION_LOCKED: 7,
  BE_PLATFORM_UNSUPPORTED: 1,
  BE_INTERNAL_STATE_CORRUPT: 1,
} as const satisfies Record<ErrorCode, number>;

export const ERROR_DEFAULT_MESSAGES = {
  BE_USAGE_INVALID: 'Command arguments are invalid.',
  BE_ROOT_NOT_FOUND: 'Backlog root was not found.',
  BE_ROOT_ALREADY_EXISTS: 'Backlog root already exists.',
  BE_ROOT_NOT_EMPTY:
    'Cannot initialize backlog because the target directory contains entries that conflict with backlog-managed artifacts.',
  BE_INVALID_JSON: 'Input JSON is invalid.',
  BE_SCHEMA_INVALID: 'Input does not match the required schema.',
  BE_INPUT_FILE_NOT_FOUND: 'Input file was not found.',
  BE_SOURCE_NOT_FOUND: 'Source was not found.',
  BE_SOURCE_FILE_MISSING: 'Registered source file is missing on disk.',
  BE_SOURCE_READ_FAILED: 'Registered source file could not be read safely.',
  BE_SOURCE_KIND_INVALID: 'Source kind is invalid.',
  BE_SOURCE_AUTHORITY_INVALID: 'Source authority is invalid.',
  BE_PACKET_ITEM_ALREADY_EXISTS: 'Packet contains item_key that already exists in the backlog.',
  BE_PACKET_DUPLICATE_ITEM_KEYS: 'Packet contains duplicate item_key values.',
  BE_CONTEXT_CONFLICT_GLOSSARY: 'Packet glossary conflicts with existing backlog glossary.',
  BE_CONTEXT_CONFLICT_ENTITY: 'Packet context entity conflicts with existing immutable context.',
  BE_DEPENDENCY_NOT_FOUND: 'Dependency item_key was not found.',
  BE_PATCH_TARGET_NOT_FOUND: 'Patch target item was not found.',
  BE_PATCH_ID_CONFLICT: 'Patch ID already exists in applied registry.',
  BE_PATCH_SEQUENCE_CONFLICT: 'Patch sequence is not monotonic.',
  BE_PATCH_OPERATION_INVALID: 'Patch operation is invalid for this command.',
  BE_TODO_REFRESH_MANAGED: 'Refresh-managed review todo cannot be removed through patch-item.',
  BE_TODO_NOT_FOUND: 'Todo was not found.',
  BE_ITEM_NOT_FOUND: 'Item was not found.',
  BE_CANONICAL_WRITE_FAILED: 'Failed to write canonical artifact.',
  BE_REPORT_WRITE_FAILED: 'Failed to write report artifact.',
  BE_TEMPLATE_OUTPUT_INVALID: 'Template output path is invalid.',
  BE_DELETE_CONFIRM_REQUIRED: 'Destructive command requires explicit confirmation.',
  BE_MUTATION_LOCKED: 'Another mutating command is already running for this backlog root.',
  BE_PLATFORM_UNSUPPORTED:
    'This operation requires anchored directory handling that is unsupported on the current platform.',
  BE_INTERNAL_STATE_CORRUPT: 'Internal runtime state is corrupt.',
} as const satisfies Record<ErrorCode, string>;

export const INTERNAL_ERROR_CODES = new Set<ErrorCode>([
  'BE_CANONICAL_WRITE_FAILED',
  'BE_REPORT_WRITE_FAILED',
  'BE_INTERNAL_STATE_CORRUPT',
]);
